import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'sv' | 'no' | 'da' | 'fi' | 'is';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.cart': 'Cart',
    'nav.categories': 'Categories',
    'nav.settings': 'Settings',
    'nav.wishlist': 'Wishlist',
    'nav.customer': 'Customer',
    'nav.menu': 'Menu',
    'categories.bags': 'Bags',
    'categories.wallets': 'Wallets',
    'categories.belts': 'Belts',
    'categories.jackets': 'Jackets',
    'categories.accessories': 'Accessories',
    'search.placeholder': 'Search for products...',
    'search.title': 'Search Products',
    'promo.freeShipping': 'Free Shipping on Orders Over €100',
    'promo.support': '24/7 Customer Support',
    'theme.light': 'Light Mode',
    'theme.dark': 'Dark Mode',
    'hero.title': 'Premium Nordic Skin Products',
    'hero.subtitle': 'Handcrafted with Nordic tradition and timeless style',
    'hero.cta': 'Shop Collection',
    'hero.authentic': 'Authentic Nordic Craftsmanship',
    'hero.from': 'From the Heart of Scandinavia',
    'hero.description': 'Handcrafted with centuries-old techniques, our products embody the Nordic spirit of quality, durability, and timeless design.',
    'hero.explore': 'Explore Collection',
    'hero.story': 'Our Story',
    'products.title': 'Our Collection',
    'products.filter': 'Filter by Category',
    'products.all': 'All Products',
    'products.bags': 'Bags',
    'products.wallets': 'Wallets',
    'products.belts': 'Belts',
    'products.jackets': 'Jackets',
    'products.accessories': 'Accessories',
    'product.addToCart': 'Add to Cart',
    'product.price': 'Price',
    'product.size': 'Size',
    'product.color': 'Color',
    'product.selectVariant': 'Please select a product variant',
    'admin.title': 'Admin Dashboard',
    'admin.products': 'Manage Products',
    'admin.orders': 'Orders',
    'admin.customers': 'Customers',
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'about.title': 'About Nordic Skin',
    'about.subtitle': 'Crafting premium goods with Nordic tradition and timeless elegance since 1952.',
    'about.story': 'Our Story',
    'about.story.p1': 'Founded in the heart of Stockholm, Nordic Skin began as a small family workshop dedicated to preserving the ancient art of Nordic craftsmanship. Our founder, Erik Andersson, believed that true quality comes from patience, skill, and respect for natural materials.',
    'about.story.p2': 'Today, we continue this tradition, combining time-honored techniques with modern design to create products that tell a story of Nordic heritage and exceptional quality.',
    'about.values': 'Our Values',
    'about.heritage': 'Nordic Heritage',
    'about.heritage.desc': 'Rooted in Scandinavian tradition and craftsmanship',
    'about.sustainability': 'Sustainability',
    'about.sustainability.desc': 'Ethical sourcing and environmentally conscious practices',
    'about.quality': 'Quality',
    'about.quality.desc': 'Meticulous attention to detail in every piece',
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Have a question or want to learn more about our handcrafted Nordic Skin products? We\'d love to hear from you.',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.info': 'Contact Information',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.hours': 'Business Hours',
    'footer.brand.desc': 'Handcrafted goods with Nordic tradition and timeless style.',
    'footer.quicklinks': 'Quick Links',
    'footer.categories': 'Categories',
    'footer.contact': 'Contact',
    'footer.company': 'Nordic Skin Co.',
    'footer.location': 'Stockholm, Sweden',
    'footer.copyright': '© 2024 Nordic Skin. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'common.featured': 'Featured Collection',
    'common.new': 'New',
    'common.viewDetails': 'View Details',
    'common.discover': 'Discover our collection of handcrafted Nordic Skin products, each piece telling its own story of Nordic tradition.',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.logout': 'Logout',
    'auth.loginGoogle': 'Continue with Google',
    'auth.loginCustomer': 'Customer Login',
    'auth.loginAdmin': 'Admin Login',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.name': 'Name',
    'auth.createAccount': 'Create Account',
    'auth.haveAccount': 'Already have an account?',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.resetHere': 'Reset Here',
    // Custom Jacket Configurator
    'customJacket.title': 'Customize Your Leather Jacket',
    'customJacket.subtitle': 'Select your preferences and submit your custom order.',
    'customJacket.color': 'Color',
    'customJacket.size': 'Size',
    'customJacket.material': 'Material',
    'customJacket.lining': 'Lining',
    'customJacket.monogram': 'Monogram (optional)',
    'customJacket.notes': 'Special Instructions',
    'customJacket.submit': 'Submit Custom Order',
    'customJacket.thankYou': 'Thank you for your custom order! We will contact you soon.',
    'auth.profile': 'Profile',
    'auth.updateProfile': 'Update Profile',
    'auth.saveChanges': 'Save Changes',
    'auth.loading': 'Loading account...',
    'toast.loginSuccess': 'Successfully logged in!',
    'toast.signupSuccess': 'Account created successfully!',
    'toast.logoutSuccess': 'Successfully logged out!',
    'toast.profileUpdated': 'Profile updated successfully!',
    'toast.cartUpdated': 'Cart updated successfully!',
    'toast.addedToCart': 'Added to cart!',
    'toast.itemRemoved': 'Item removed from cart',
    'toast.error': 'An error occurred. Please try again.',
    'toast.loginError': 'Login failed. Please check your credentials.',
    'toast.signupError': 'Sign up failed. Please try again.',
    'toast.cartError': 'Failed to update cart.',
    'error.unauthorized': 'Unauthorized access',
    'error.notFound': 'Page not found',
    'error.serverError': 'Server error',
    'error.networkError': 'Network error',
    'error.validationError': 'Validation error',
    'error.generic': 'Something went wrong',
    'cart.quantity': 'Quantity',
    'cart.remove': 'Remove',
    'cart.update': 'Update',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.tax': 'Tax',
    'cart.loading': 'Loading...',
    'cart.continue': 'Continue Shopping',
    'cart.freeShipping': 'Free shipping on orders over €100',
    'cart.returnPolicy': '30-day return policy',
    'cart.securePayment': 'Secure payment processing',
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.none': 'None',
    'common.ok': 'OK',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'admin.dashboard': 'Dashboard',
    'admin.addProduct': 'Add Product',
    'admin.editProduct': 'Edit Product',
    'admin.deleteProduct': 'Delete Product',
    'admin.manageUsers': 'Manage Users',
    'address.title': 'Addresses',
    'address.add': 'Add Address',
    'address.edit': 'Edit Address',
    'address.delete': 'Delete Address',
    'address.setDefault': 'Set as Default',
    'address.default': 'Default',
    'address.type': 'Address Type',
    'address.home': 'Home',
    'address.work': 'Work',
    'address.other': 'Other',
    'address.label': 'Label',
    'address.street': 'Street Address',
    'address.city': 'City',
    'address.state': 'State/Province',
    'address.postalCode': 'Postal Code',
    'address.country': 'Country',
    'address.save': 'Save Address',
    'address.cancel': 'Cancel',
    'address.confirmDelete': 'Are you sure you want to delete this address?',
    'address.mustHaveOne': 'You must have at least one address',
    'address.addSuccess': 'Address added successfully!',
    'address.updateSuccess': 'Address updated successfully!',
    'address.deleteSuccess': 'Address deleted successfully!',
    'address.defaultSuccess': 'Default address updated!',
    'admin.settings': 'Settings',
    'admin.reports': 'Reports',
    'product.details': 'Product Details',
    'product.description': 'Description',
    'product.specifications': 'Specifications',
    'product.reviews': 'Reviews',
    'product.inStock': 'In Stock',
    'product.outOfStock': 'Out of Stock',
    'product.selectSize': 'Select Size',
    'product.selectColor': 'Select Color',
    'product.selectSizeAndColor': 'Please select size and color',
    'product.chooseVariant': 'Choose your variant',
    'common.share': 'Share',
    'common.each': 'each',
    // About page specific translations
    'about.hero.title': 'Our Story',
    'about.hero.subtitle': 'A legacy of authentic Nordic craftsmanship spanning over a century',
    'about.timeline.title': 'Journey Through Time',
    'about.timeline.1892.title': 'Nordic Traditions Begin',
    'about.timeline.1892.desc': 'Founded in the heart of Scandinavia, our craft began with traditional Nordic techniques passed down through generations.',
    'about.timeline.1950.title': 'Artisan Heritage',
    'about.timeline.1950.desc': 'Three generations of master craftsmen refined our techniques, establishing the quality standards that define our brand today.',
    'about.timeline.1985.title': 'Sustainable Innovation',
    'about.timeline.1985.desc': 'We pioneered eco-friendly production methods, becoming the first Nordic brand to achieve carbon-neutral production.',
    'about.timeline.2020.title': 'Modern Excellence',
    'about.timeline.2020.desc': 'Today, we blend traditional craftsmanship with modern design, creating timeless pieces for the contemporary Nordic lifestyle.',
    'about.values.title': 'Our Values',
    'about.values.heritage.title': 'Nordic Heritage',
    'about.values.heritage.desc': 'Rooted in Scandinavian traditions and time-tested craftsmanship techniques.',
    'about.values.sustainability.title': 'Sustainability',
    'about.values.sustainability.desc': 'Committed to environmental responsibility and ethical sourcing practices.',
    'about.values.quality.title': 'Quality',
    'about.values.quality.desc': 'Uncompromising standards ensuring every piece lasts for generations.',
    'about.timeline.established': 'Est.',
    // Error pages
    'error.404.title': 'Page Not Found',
    'error.404.desc': 'The page you\'re looking for doesn\'t exist or has been moved.',
    'error.404.goHome': 'Go to Home',
    'error.404.goBack': 'Go Back'
  },
  sv: {
    'nav.home': 'Hem',
    'nav.products': 'Produkter',
    'nav.about': 'Om oss',
    'nav.contact': 'Kontakt',
    'nav.admin': 'Admin',
    'nav.cart': 'Kundvagn',
    'nav.categories': 'Kategorier',
    'nav.settings': 'Inställningar',
    'nav.wishlist': 'Önskelista',
    'nav.customer': 'Kund',
    'nav.menu': 'Meny',
    'categories.bags': 'Väskor',
    'categories.wallets': 'Plånböcker',
    'categories.belts': 'Bälten',
    'categories.jackets': 'Jackor',
    'categories.accessories': 'Tillbehör',
    'search.placeholder': 'Sök efter produkter...',
    'search.title': 'Sök Produkter',
    'promo.freeShipping': 'Fri frakt på beställningar över €100',
    'promo.support': '24/7 Kundsupport',
    'theme.light': 'Ljust läge',
    'theme.dark': 'Mörkt läge',
    'hero.title': 'Högkvalitativa Lädervaror',
    'hero.subtitle': 'Handgjorda med nordisk tradition och tidlös stil',
    'hero.cta': 'Handla Kollektion',
    'hero.authentic': 'Äkta Nordiskt Hantverk',
    'hero.from': 'Från Skandinaviens Hjärta',
    'hero.description': 'Handgjorda med århundraden gamla tekniker, våra lädervaror förkroppsligar den nordiska andan av kvalitet, hållbarhet och tidlös design.',
    'hero.explore': 'Utforska Kollektion',
    'hero.story': 'Vår Historia',
    'products.title': 'Vår Kollektion',
    'products.filter': 'Filtrera efter Kategori',
    'products.all': 'Alla Produkter',
    'products.bags': 'Väskor',
    'products.wallets': 'Plånböcker',
    'products.belts': 'Bälten',
    'products.jackets': 'Jackor',
    'products.accessories': 'Tillbehör',
    'product.addToCart': 'Lägg i Kundvagn',
    'product.price': 'Pris',
    'product.size': 'Storlek',
    'product.color': 'Färg',
    'product.selectVariant': 'Välj en produktvariant',
    'admin.title': 'Admin Panel',
    'admin.products': 'Hantera Produkter',
    'admin.orders': 'Beställningar',
    'admin.customers': 'Kunder',
    'cart.title': 'Kundvagn',
    'cart.empty': 'Din kundvagn är tom',
    'cart.total': 'Totalt',
    'cart.checkout': 'Checkout',
    'about.title': 'Om Nordic Skin',
    'about.subtitle': 'Skapar förstklassiga lädervaror med nordisk tradition och tidlös elegans sedan 1952.',
    'about.story': 'Vår Historia',
    'about.story.p1': 'Grundat i hjärtat av Stockholm började Nordic Skin som en liten familjeverkstad dedikerad till att bevara den gamla konsten av läderhantverk. Vår grundare, Erik Andersson, trodde att verklig kvalitet kommer från tålamod, skicklighet och respekt för naturliga material.',
    'about.story.p2': 'Idag fortsätter vi denna tradition och kombinerar tidstestade tekniker med modern design för att skapa lädervaror som berättar en historia om nordiskt arv och exceptionell kvalitet.',
    'about.values': 'Våra Värderingar',
    'about.heritage': 'Nordiskt Arv',
    'about.heritage.desc': 'Rotad i skandinavisk tradition och hantverk',
    'about.sustainability': 'Hållbarhet',
    'about.sustainability.desc': 'Etisk inköp och miljömedvetna metoder',
    'about.quality': 'Kvalitet',
    'about.quality.desc': 'Noggrann uppmärksamhet på detaljer i varje stycke',
    'contact.title': 'Kontakta Oss',
    'contact.subtitle': 'Har du en fråga eller vill veta mer om våra handgjorda nordiska lädervaror? Vi skulle gärna höra från dig.',
    'contact.form.name': 'Fullständigt Namn',
    'contact.form.email': 'E-postadress',
    'contact.form.subject': 'Ämne',
    'contact.form.message': 'Meddelande',
    'contact.form.send': 'Skicka Meddelande',
    'contact.info': 'Kontaktinformation',
    'contact.address': 'Adress',
    'contact.phone': 'Telefon',
    'contact.email': 'E-post',
    'contact.hours': 'Öppettider',
    'footer.brand.desc': 'Handgjorda lädervaror med nordisk tradition och tidlös stil.',
    'footer.quicklinks': 'Snabblänkar',
    'footer.categories': 'Kategorier',
    'footer.contact': 'Kontakt',
    'footer.company': 'Nordic Skin Co.',
    'footer.location': 'Stockholm, Sverige',
    'footer.copyright': '© 2024 Nordic Skin. Alla rättigheter förbehållna.',
    'footer.privacy': 'Sekretesspolicy',
    'footer.terms': 'Användarvillkor',
    'common.featured': 'Utvald Kollektion',
    'common.new': 'Ny',
    'common.viewDetails': 'Visa Detaljer',
    'common.discover': 'Upptäck vår kollektion av handgjorda lädervaror, varje stycke berättar sin egen historia om nordisk tradition.',
    'auth.login': 'Logga in',
    'auth.signup': 'Registrera',
    'auth.logout': 'Logga ut',
    'auth.loginGoogle': 'Fortsätt med Google',
    'auth.loginCustomer': 'Kund Inloggning',
    'auth.loginAdmin': 'Admin Inloggning',
    'auth.email': 'E-post',
    'auth.password': 'Lösenord',
    'auth.confirmPassword': 'Bekräfta Lösenord',
    'auth.name': 'Namn',
    'auth.createAccount': 'Skapa Konto',
    'auth.haveAccount': 'Har du redan ett konto?',
    'auth.noAccount': 'Har du inget konto?',
    'auth.forgotPassword': 'Glömt ditt lösenord?',
    'auth.resetHere': 'Återställ här',
    // Custom Jacket Configurator
    'customJacket.title': 'Designa din skinnjacka',
    'customJacket.subtitle': 'Välj dina preferenser och skicka din specialbeställning.',
    'customJacket.color': 'Färg',
    'customJacket.size': 'Storlek',
    'customJacket.material': 'Material',
    'customJacket.lining': 'Foder',
    'customJacket.monogram': 'Monogram (valfritt)',
    'customJacket.notes': 'Speciella instruktioner',
    'customJacket.submit': 'Skicka specialbeställning',
    'customJacket.thankYou': 'Tack för din specialbeställning! Vi kontaktar dig snart.',
    'auth.profile': 'Profil',
    'auth.updateProfile': 'Uppdatera Profil',
    'auth.saveChanges': 'Spara Ändringar',
    'auth.loading': 'Laddar konto...',
    'toast.loginSuccess': 'Lyckad inloggning!',
    'toast.signupSuccess': 'Konto skapat framgångsrikt!',
    'toast.logoutSuccess': 'Lyckad utloggning!',
    'toast.profileUpdated': 'Profil uppdaterad framgångsrikt!',
    'toast.cartUpdated': 'Kundvagn uppdaterad framgångsrikt!',
    'toast.addedToCart': 'Tillagd i kundvagn!',
    'toast.itemRemoved': 'Vara borttagen från kundvagnen',
    'toast.error': 'Ett fel inträffade. Försök igen.',
    'toast.loginError': 'Inloggning misslyckades. Kontrollera dina uppgifter.',
    'toast.signupError': 'Registrering misslyckades. Försök igen.',
    'toast.cartError': 'Misslyckades att uppdatera kundvagn.',
    'error.unauthorized': 'Obehörig åtkomst',
    'error.notFound': 'Sidan hittades inte',
    'error.serverError': 'Serverfel',
    'error.networkError': 'Nätverksfel',
    'error.validationError': 'Valideringsfel',
    'error.generic': 'Något gick fel',
    'cart.quantity': 'Antal',
    'cart.remove': 'Ta bort',
    'cart.update': 'Uppdatera',
    'cart.freeShipping': 'Fri frakt på order över €100',
    'cart.returnPolicy': '30 dagars returrätt',
    'cart.securePayment': 'Säker betalningshantering',
    'cart.subtotal': 'Delsumma',
    'cart.shipping': 'Frakt',
    'cart.tax': 'Skatt',
    'cart.loading': 'Laddar...',
    'cart.continue': 'Fortsätt Handla',
    'common.loading': 'Laddar...',
    'common.save': 'Spara',
    'common.cancel': 'Avbryt',
    'common.delete': 'Radera',
    'common.edit': 'Redigera',
    'common.close': 'Stäng',
    'common.yes': 'Ja',
    'common.no': 'Nej',
    'common.none': 'Ingen',
    'common.ok': 'OK',
    'common.back': 'Tillbaka',
    'common.next': 'Nästa',
    'common.previous': 'Föregående',
    'admin.dashboard': 'Instrumentpanel',
    'admin.addProduct': 'Lägg till Produkt',
    'admin.editProduct': 'Redigera Produkt',
    'admin.deleteProduct': 'Radera Produkt',
    'admin.manageUsers': 'Hantera Användare',
    'address.title': 'Adresser',
    'address.add': 'Lägg till Adress',
    'address.edit': 'Redigera Adress',
    'address.delete': 'Ta bort Adress',
    'address.setDefault': 'Sätt som Standard',
    'address.default': 'Standard',
    'address.type': 'Adresstyp',
    'address.home': 'Hem',
    'address.work': 'Arbete',
    'address.other': 'Annat',
    'address.label': 'Etikett',
    'address.street': 'Gatuadress',
    'address.city': 'Stad',
    'address.state': 'Län/Region',
    'address.postalCode': 'Postnummer',
    'address.country': 'Land',
    'address.save': 'Spara Adress',
    'address.cancel': 'Avbryt',
    'address.confirmDelete': 'Är du säker på att du vill ta bort denna adress?',
    'address.mustHaveOne': 'Du måste ha minst en adress',
    'address.addSuccess': 'Adress tillagd framgångsrikt!',
    'address.updateSuccess': 'Adress uppdaterad framgångsrikt!',
    'address.deleteSuccess': 'Adress borttagen framgångsrikt!',
    'address.defaultSuccess': 'Standardadress uppdaterad!',
    'admin.settings': 'Inställningar',
    'admin.reports': 'Rapporter',
    'product.details': 'Produktdetaljer',
    'product.description': 'Beskrivning',
    'product.specifications': 'Specifikationer',
    'product.reviews': 'Recensioner',
    'product.inStock': 'I lager',
    'product.outOfStock': 'Slut i lager',
    'product.selectSize': 'Välj storlek',
    'product.selectColor': 'Välj färg',
    'product.selectSizeAndColor': 'Välj storlek och färg',
    'product.chooseVariant': 'Välj din variant',
    'common.share': 'Dela',
    'common.each': 'vardera',
    // About page specific translations
    'about.hero.title': 'Vår Historia',
    'about.hero.subtitle': 'Ett arv av äkta nordiskt hantverk som sträcker sig över ett sekel',
    'about.timeline.title': 'Resa Genom Tiden',
    'about.timeline.1892.title': 'Nordiska Traditioner Börjar',
    'about.timeline.1892.desc': 'Grundat i hjärtat av Skandinavien började vårt hantverk med traditionella läderbearbetningstekniker som förts vidare genom generationer.',
    'about.timeline.1950.title': 'Hantverkarnas Arv',
    'about.timeline.1950.desc': 'Tre generationer av mästerhantverkare förfinade våra tekniker och etablerade de kvalitetsstandarder som definierar vårt varumärke idag.',
    'about.timeline.1985.title': 'Hållbar Innovation',
    'about.timeline.1985.desc': 'Vi var pionjärer inom miljövänliga läderbearbetningsmetoder och blev det första nordiska varumärket att uppnå koldioxidneutral produktion.',
    'about.timeline.2020.title': 'Modern Excellens',
    'about.timeline.2020.desc': 'Idag blandar vi traditionellt hantverk med modern design för att skapa tidlösa stycken för den samtida nordiska livsstilen.',
    'about.values.title': 'Våra Värderingar',
    'about.values.heritage.title': 'Nordiskt Arv',
    'about.values.heritage.desc': 'Rotat i skandinaviska traditioner och tidstestade hantverkstekniker.',
    'about.values.sustainability.title': 'Hållbarhet',
    'about.values.sustainability.desc': 'Engagerade i miljöansvar och etiska inköpsmetoder.',
    'about.values.quality.title': 'Kvalitet',
    'about.values.quality.desc': 'Kompromisslösa standarder som säkerställer att varje stycke håller i generationer.',
    'about.timeline.established': 'Grundad',
    // Error pages
    'error.404.title': 'Sidan Hittades Inte',
    'error.404.desc': 'Sidan du letar efter finns inte eller har flyttats.',
    'error.404.goHome': 'Gå till Hem',
    'error.404.goBack': 'Gå Tillbaka',
    // Error pages
    'error.notFoundTitle': 'Sidan hittades inte',
    'error.notFoundDesc': 'Sidan du letar efter finns inte eller har flyttats.',
    'error.goHome': 'Gå till startsidan',
    'error.goBack': 'Gå tillbaka'
  },
  no: {
    'nav.home': 'Hjem',
    'nav.products': 'Produkter',
    'nav.about': 'Om oss',
    'nav.contact': 'Kontakt',
    'nav.admin': 'Admin',
    'nav.cart': 'Handlekurv',
    'nav.categories': 'Kategorier',
    'nav.settings': 'Innstillinger',
    'nav.wishlist': 'Ønskeliste',
    'nav.menu': 'Meny',
    'nav.customer': 'Kunde',
    'categories.bags': 'Vesker',
    'categories.wallets': 'Lommebøker',
    'categories.belts': 'Belter',
    'categories.jackets': 'Jakker',
    'categories.accessories': 'Tilbehør',
    'search.placeholder': 'Søk etter produkter...',
    'search.title': 'Søk Produkter',
    'promo.freeShipping': 'Gratis frakt på bestillinger over €100',
    'promo.support': '24/7 Kundestøtte',
    'theme.light': 'Lys modus',
    'theme.dark': 'Mørk modus',
    'hero.title': 'Premium Lærvarer',
    'hero.subtitle': 'Håndlaget med nordisk tradisjon og tidløs stil',
    'hero.cta': 'Handle Kolleksjon',
    'hero.authentic': 'Autentisk Nordisk Håndverk',
    'hero.from': 'Fra Skandinavias Hjerte',
    'hero.description': 'Håndlaget med århundrer gamle teknikker, våre lærvarer legemliggjør den nordiske ånden av kvalitet, holdbarhet og tidløs design.',
    'hero.explore': 'Utforsk Kolleksjon',
    'hero.story': 'Vår Historie',
    'products.title': 'Vår Kolleksjon',
    'products.filter': 'Filtrer etter Kategori',
    'products.all': 'Alle Produkter',
    'products.bags': 'Vesker',
    'products.wallets': 'Lommebøker',
    'products.belts': 'Belter',
    'products.jackets': 'Jakker',
    'products.accessories': 'Tilbehør',
    'product.addToCart': 'Legg i Handlekurv',
    'product.price': 'Pris',
    'product.size': 'Størrelse',
    'product.color': 'Farge',
    'admin.title': 'Admin Panel',
    'admin.products': 'Administrer Produkter',
    'admin.orders': 'Bestillinger',
    'admin.customers': 'Kunder',
    'cart.title': 'Handlekurv',
    'cart.empty': 'Handlekurven din er tom',
    'cart.total': 'Totalt',
    'cart.checkout': 'Til kassen',
    'about.title': 'Om Nordic Skin',
    'about.subtitle': 'Lager premium lærvarer med nordisk tradisjon og tidløs eleganse siden 1952.',
    'about.story': 'Vår Historie',
    'about.story.p1': 'Grunnlagt i hjertet av Stockholm begynte Nordic Skin som en liten familieverksted dedikert til å bevare den gamle kunsten av lærhåndverk. Vår grunnlegger, Erik Andersson, trodde at ekte kvalitet kommer fra tålmodighet, ferdighet og respekt for naturlige materialer.',
    'about.story.p2': 'I dag fortsetter vi denne tradisjonen og kombinerer tidserprobde teknikker med moderne design for å lage lærvarer som forteller en historie om nordisk arv og eksepsjonell kvalitet.',
    'about.values': 'Våre Verdier',
    'about.heritage': 'Nordisk Arv',
    'about.heritage.desc': 'Forankret i skandinavisk tradisjon og håndverk',
    'about.sustainability': 'Bærekraft',
    'about.sustainability.desc': 'Etisk innkjøp og miljøbevisste praksiser',
    'about.quality': 'Kvalitet',
    'about.quality.desc': 'Grundig oppmerksomhet på detaljer i hvert stykke',
    'contact.title': 'Ta Kontakt',
    'contact.subtitle': 'Har du et spørsmål eller vil lære mer om våre håndlagede nordiske lærvarer? Vi vil gjerne høre fra deg.',
    'contact.form.name': 'Fullt Navn',
    'contact.form.email': 'E-postadresse',
    'contact.form.subject': 'Emne',
    'contact.form.message': 'Melding',
    'contact.form.send': 'Send Melding',
    'contact.info': 'Kontaktinformasjon',
    'contact.address': 'Adresse',
    'contact.phone': 'Telefon',
    'contact.email': 'E-post',
    'contact.hours': 'Åpningstider',
    'footer.brand.desc': 'Håndlagede lærvarer med nordisk tradisjon og tidløs stil.',
    'footer.quicklinks': 'Hurtiglenker',
    'footer.categories': 'Kategorier',
    'footer.contact': 'Kontakt',
    'footer.company': 'Nordic Skin Co.',
    'footer.location': 'Stockholm, Sverige',
    'footer.copyright': '© 2024 Nordic Skin. Alle rettigheter forbeholdt.',
    'footer.privacy': 'Personvernpolicy',
    'footer.terms': 'Vilkår for tjeneste',
    'common.featured': 'Utvalgt Samling',
    'common.new': 'Ny',
    'common.viewDetails': 'Se Detaljer',
    'common.discover': 'Oppdag vår samling av håndlagede lærvarer, hvert stykke forteller sin egen historie om nordisk tradisjon.',
    'auth.login': 'Logg inn',
    'auth.signup': 'Registrer',
    'auth.logout': 'Logg ut',
    'auth.loginGoogle': 'Fortsett med Google',
    'auth.loginCustomer': 'Kunde Innlogging',
    'auth.loginAdmin': 'Admin Innlogging',
    'auth.email': 'E-post',
    'auth.password': 'Passord',
    'auth.confirmPassword': 'Bekreft Passord',
    'auth.name': 'Navn',
    'auth.createAccount': 'Opprett Konto',
    'auth.haveAccount': 'Har du allerede en konto?',
    'auth.noAccount': 'Har du ikke en konto?',
    'auth.profile': 'Profil',
    'auth.updateProfile': 'Oppdater Profil',
    'auth.saveChanges': 'Lagre Endringer',
    'auth.loading': 'Laster konto...',
    'toast.loginSuccess': 'Vellykket innlogging!',
    'toast.signupSuccess': 'Konto opprettet!',
    'toast.logoutSuccess': 'Vellykket utlogging!',
    'toast.profileUpdated': 'Profil oppdatert!',
    'toast.cartUpdated': 'Handlekurv oppdatert!',
    'toast.addedToCart': 'Lagt til i handlekurv!',
    'toast.error': 'En feil oppstod. Prøv igjen.',
    'toast.loginError': 'Innlogging mislyktes. Sjekk påloggingsdetaljene.',
    'toast.signupError': 'Registrering mislyktes. Prøv igjen.',
    'toast.cartError': 'Kunne ikke oppdatere handlekurv.',
    'error.unauthorized': 'Uautorisert tilgang',
    'error.notFound': 'Side ikke funnet',
    'error.serverError': 'Serverfeil',
    'error.networkError': 'Netverksfeil',
    'error.validationError': 'Valideringsfeil',
    'error.generic': 'Noe gikk galt',
    'cart.quantity': 'Antall',
    'cart.remove': 'Fjern',
    'cart.update': 'Oppdater',
    'cart.subtotal': 'Delsum',
    'cart.shipping': 'Frakt',
    'cart.tax': 'Avgift',
    'cart.loading': 'Laster...',
    'cart.continue': 'Fortsett å Handle',
    'common.loading': 'Laster...',
    'common.save': 'Lagre',
    'common.cancel': 'Avbryt',
    'common.delete': 'Slett',
    'common.edit': 'Rediger',
    'common.close': 'Lukk',
    'common.yes': 'Ja',
    'common.no': 'Nei',
    'common.none': 'Ingen',
    'common.ok': 'OK',
    'common.back': 'Tilbake',
    'common.next': 'Neste',
    'common.previous': 'Forrige',
    'admin.dashboard': 'Kontrollpanel',
    'admin.addProduct': 'Legg til Produkt',
    'admin.editProduct': 'Rediger Produkt',
    'admin.deleteProduct': 'Slett Produkt',
    'admin.manageUsers': 'Administrer Brukere',
    'address.title': 'Adresser',
    'address.add': 'Legg til Adresse',
    'address.edit': 'Rediger Adresse',
    'address.delete': 'Ta bort Adresse',
    'address.setDefault': 'Sett som Standard',
    'address.default': 'Standard',
    'address.type': 'Adressetype',
    'address.home': 'Hjem',
    'address.work': 'Arbeid',
    'address.other': 'Annet',
    'address.label': 'Etikett',
    'address.street': 'Gateadresse',
    'address.city': 'By',
    'address.state': 'Fylke/Provins',
    'address.postalCode': 'Postnummer',
    'address.country': 'Land',
    'address.save': 'Lagre Adresse',
    'address.cancel': 'Avbryt',
    'address.confirmDelete': 'Er du sikker på at du vil slette denne adressen?',
    'address.mustHaveOne': 'Du må ha minst én adresse',
    'address.addSuccess': 'Adresse lagt til!',
    'address.updateSuccess': 'Adresse oppdatert!',
    'address.deleteSuccess': 'Adresse slettet!',
    'address.defaultSuccess': 'Standardadresse oppdatert!',
    'admin.settings': 'Innstillinger',
    'admin.reports': 'Rapporter',
    'product.details': 'Produktdetaljer',
    'product.description': 'Beskrivelse',
    'product.specifications': 'Spesifikasjoner',
    'product.reviews': 'Anmeldelser',
    'product.inStock': 'På lager',
    'product.outOfStock': 'Utsolgt',
    'product.selectSize': 'Velg størrelse',
    'product.selectColor': 'Velg farge',
    'product.selectSizeAndColor': 'Velg størrelse og farge',
    'product.chooseVariant': 'Velg din variant',
    'common.share': 'Del',
    'common.each': 'hver',
    // About page specific translations
    'about.hero.title': 'Vår Historie',
    'about.hero.subtitle': 'Ett arv av autentisk nordisk håndverk som strekker seg over et århundre',
    'about.timeline.title': 'Reise Gjennom Tid',
    'about.timeline.1892.title': 'Nordiske Traditioner Begynner',
    'about.timeline.1892.desc': 'Grunnlagt i hjertet av Skandinavia begynte vårt håndverk med tradisjonelle lærbearbeidingsteknikker som er blitt videreført gjennom generasjoner.',
    'about.timeline.1950.title': 'Håndverkarens Arv',
    'about.timeline.1950.desc': 'Tre generasjoner av mesterhåndverkere raffinerte våre teknikker og etablerte kvalitetsstandardene som definerer vårt merke i dag.',
    'about.timeline.1985.title': 'Bærekraftig Innovasjon',
    'about.timeline.1985.desc': 'Vi var pionerer innen miljøvennlige lærbearbeidingsmetoder og ble det første nordiske merket som oppnådde karbonnøytral produksjon.',
    'about.timeline.2020.title': 'Moderne Fortreffelighet',
    'about.timeline.2020.desc': 'I dag blander vi tradisjonelt håndverk med moderne design for å skape tidløse stykker for den moderne nordiske livsstilen.',
    'about.values.title': 'Våre Verdier',
    'about.values.heritage.title': 'Nordisk Arv',
    'about.values.heritage.desc': 'Forankret i skandinaviske tradisjoner og tidstestede håndverksteknikker.',
    'about.values.sustainability.title': 'Bærekraft',
    'about.values.sustainability.desc': 'Forpliktet til miljøansvar og etiske innkjøpspraksis.',
    'about.values.quality.title': 'Kvalitet',
    'about.values.quality.desc': 'Kompromissløse standarder som sikrer at hvert stykke varer i generasjoner.',
    'about.timeline.established': 'Grunnlagt',
    // Error pages
    'error.404.title': 'Side Ikke Funnet',
    'error.404.desc': 'Siden du leter etter finnes ikke eller har blitt flyttet.',
    'error.404.goHome': 'Gå til Hjem',
    'error.404.goBack': 'Gå Tilbake',
    // Error pages
    'error.notFoundTitle': 'Siden ble ikke funnet',
    'error.notFoundDesc': 'Siden du leter etter eksisterer ikke eller har blitt flyttet.',
    'error.goHome': 'Gå til startsiden',
    'error.goBack': 'Gå tilbake'
  },
  da: {
    'nav.home': 'Hjem',
    'nav.products': 'Produkter',
    'nav.about': 'Om os',
    'nav.contact': 'Kontakt',
    'nav.admin': 'Admin',
    'nav.cart': 'Indkøbskurv',
    'nav.categories': 'Kategorier',
    'nav.settings': 'Indstillinger',
    'nav.wishlist': 'Ønskeliste',
    'nav.menu': 'Menu',
    'nav.customer': 'Kunde',
    'categories.bags': 'Tasker',
    'categories.wallets': 'Tegnebøger',
    'categories.belts': 'Bælter',
    'categories.jackets': 'Jakker',
    'categories.accessories': 'Tilbehør',
    'search.placeholder': 'Søg efter produkter...',
    'search.title': 'Søg Produkter',
    'promo.freeShipping': 'Gratis fragt på bestillinger over €100',
    'promo.support': '24/7 Kundesupport',
    'theme.light': 'Lys tilstand',
    'theme.dark': 'Mørk tilstand',
    'hero.title': 'Premium Lædervarer',
    'hero.subtitle': 'Håndlavet med nordisk tradition og tidløs stil',
    'hero.cta': 'Shop Kollektion',
    'hero.authentic': 'Autentisk Nordisk Håndværk',
    'hero.from': 'Fra Skandinaviens Hjerte',
    'hero.description': 'Håndlavet med århundredgamle teknikker, vores lædervarer legemliggør den nordiske ånd af kvalitet, holdbarhed og tidløst design.',
    'hero.explore': 'Udforsk Kollektion',
    'hero.story': 'Vores Historie',
    'products.title': 'Vores Kollektion',
    'products.filter': 'Filtrer efter Kategori',
    'products.all': 'Alle Produkter',
    'products.bags': 'Tasker',
    'products.wallets': 'Tegnebøger',
    'products.belts': 'Bælter',
    'products.jackets': 'Jakker',
    'products.accessories': 'Tilbehør',
    'product.addToCart': 'Tilføj til Kurv',
    'product.price': 'Pris',
    'product.size': 'Størrelse',
    'product.color': 'Farve',
    'admin.title': 'Admin Panel',
    'admin.products': 'Administrer Produkter',
    'admin.orders': 'Ordrer',
    'admin.customers': 'Kunder',
    'cart.title': 'Indkøbskurv',
    'cart.empty': 'Din indkøbskurv er tom',
    'cart.total': 'I alt',
    'cart.checkout': 'Til betaling',
    'about.title': 'Om Nordic Skin',
    'about.subtitle': 'Skaber premium lædervarer med nordisk tradition og tidløs elegance siden 1952.',
    'about.story': 'Vores Historie',
    'about.story.p1': 'Grundlagt i hjertet af Stockholm begyndte Nordic Skin som et lille familieværksted dedikeret til at bevare den gamle kunst af læhåndværk. Vores grundlægger, Erik Andersson, troede på at ægte kvalitet kommer fra tålmodighed, færdighed og respekt for naturlige materialer.',
    'about.story.p2': 'I dag fortsætter vi denne tradition og kombinerer tidstestede teknikker med moderne design for at skabe lædervarer, der fortæller en historie om nordisk arv og exceptionel kvalitet.',
    'about.values': 'Vores Værdier',
    'about.heritage': 'Nordisk Arv',
    'about.heritage.desc': 'Rodfæstet i skandinavisk tradition og håndværk',
    'about.sustainability': 'Bæredygtighed',
    'about.sustainability.desc': 'Etisk indkøb og miljøbevidste praksisser',
    'about.quality': 'Kvalitet',
    'about.quality.desc': 'Omhyggelig opmærksomhed på detaljer i hvert stykke',
    'contact.title': 'Kontakt Os',
    'contact.subtitle': 'Har du et spørgsmål eller vil vide mere om vores håndlavede nordiske lædervarer? Vi vil gerne høre fra dig.',
    'contact.form.name': 'Fulde Navn',
    'contact.form.email': 'Email Adresse',
    'contact.form.subject': 'Emne',
    'contact.form.message': 'Besked',
    'contact.form.send': 'Send Besked',
    'contact.info': 'Kontakt Information',
    'contact.address': 'Adresse',
    'contact.phone': 'Telefon',
    'contact.email': 'Email',
    'contact.hours': 'Åbningstider',
    'footer.brand.desc': 'Håndlavede lædervarer med nordisk tradition og tidløs stil.',
    'footer.quicklinks': 'Hurtige Links',
    'footer.categories': 'Kategorier',
    'footer.contact': 'Kontakt',
    'footer.company': 'Nordic Skin Co.',
    'footer.location': 'Stockholm, Sverige',
    'footer.copyright': '© 2024 Nordic Skin. Alle rettigheder forbeholdt.',
    'footer.privacy': 'Privatlivspolitik',
    'footer.terms': 'Servicevilkår',
    'common.featured': 'Udvalgt Samling',
    'common.new': 'Ny',
    'common.viewDetails': 'Se Detaljer',
    'common.discover': 'Opdag vores samling af håndlavede lædervarer, hvert stykke fortæller sin egen historie om nordisk tradition.',
    'auth.login': 'Log ind',
    'auth.signup': 'Tilmeld',
    'auth.logout': 'Log ud',
    'auth.loginGoogle': 'Fortsæt med Google',
    'auth.loginCustomer': 'Kunde Login',
    'auth.loginAdmin': 'Admin Login',
    'auth.email': 'Email',
    'auth.password': 'Adgangskode',
    'auth.confirmPassword': 'Bekræft Adgangskode',
    'auth.name': 'Navn',
    'auth.createAccount': 'Opret Konto',
    'auth.haveAccount': 'Har du allerede en konto?',
    'auth.noAccount': 'Har du ikke en konto?',
    'auth.profile': 'Profil',
    'auth.updateProfile': 'Opdater Profil',
    'auth.saveChanges': 'Gem Ændringer',
    'auth.loading': 'Indlæser konto...',
    'toast.loginSuccess': 'Succesfuldt logget ind!',
    'toast.signupSuccess': 'Konto oprettet succesfuldt!',
    'toast.logoutSuccess': 'Succesfuldt logget ud!',
    'toast.profileUpdated': 'Profil opdateret succesfuldt!',
    'toast.cartUpdated': 'Indkøbskurv opdateret succesfuldt!',
    'toast.addedToCart': 'Tilføjet til kurv!',
    'toast.error': 'Der opstod en fejl. Prøv igen.',
    'toast.loginError': 'Login mislykkedes. Tjek dine oplysninger.',
    'toast.signupError': 'Tilmelding mislykkedes. Prøv igen.',
    'toast.cartError': 'Kunne ikke opdatere indkøbskurv.',
    'error.unauthorized': 'Uautoriseret adgang',
    'error.notFound': 'Side ikke fundet',
    'error.serverError': 'Serverfejl',
    'error.networkError': 'Netværksfejl',
    'error.validationError': 'Valideringsfejl',
    'error.generic': 'Noget gik galt',
    'cart.quantity': 'Antal',
    'cart.remove': 'Fjern',
    'cart.update': 'Opdater',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Forsendelse',
    'cart.tax': 'Skat',
    'cart.loading': 'Indlæser...',
    'cart.continue': 'Fortsæt med at Handle',
    'common.loading': 'Indlæser...',
    'common.save': 'Gem',
    'common.cancel': 'Annuller',
    'common.delete': 'Slet',
    'common.edit': 'Rediger',
    'common.close': 'Luk',
    'common.yes': 'Ja',
    'common.no': 'Nej',
    'common.none': 'Ingen',
    'common.ok': 'OK',
    'common.back': 'Tilbage',
    'common.next': 'Næste',
    'common.previous': 'Forrige',
    'admin.dashboard': 'Dashboard',
    'admin.addProduct': 'Tilføj Produkt',
    'admin.editProduct': 'Rediger Produkt',
    'admin.deleteProduct': 'Slet Produkt',
    'admin.manageUsers': 'Administrer Brugere',
    'address.title': 'Adresser',
    'address.add': 'Tilføj Adresse',
    'address.edit': 'Rediger Adresse',
    'address.delete': 'Slet Adresse',
    'address.setDefault': 'Sæt som Standard',
    'address.default': 'Standard',
    'address.type': 'Adressetype',
    'address.home': 'Hjem',
    'address.work': 'Arbejde',
    'address.other': 'Andet',
    'address.label': 'Etiket',
    'address.street': 'Gadeadresse',
    'address.city': 'By',
    'address.state': 'Region/Provins',
    'address.postalCode': 'Postnummer',
    'address.country': 'Land',
    'address.save': 'Gem Adresse',
    'address.cancel': 'Annuller',
    'address.confirmDelete': 'Er du sikker på, at du vil slette denne adresse?',
    'address.mustHaveOne': 'Du skal have mindst én adresse',
    'address.addSuccess': 'Adresse tilføjet!',
    'address.updateSuccess': 'Adresse opdateret!',
    'address.deleteSuccess': 'Adresse slettet!',
    'address.defaultSuccess': 'Standardadresse opdateret!',
    'admin.settings': 'Indstillinger',
    'admin.reports': 'Rapporter',
    'product.details': 'Produktdetaljer',
    'product.description': 'Beskrivelse',
    'product.specifications': 'Specifikationer',
    'product.reviews': 'Anmeldelser',
    'product.inStock': 'På lager',
    'product.outOfStock': 'Utsolgt',
    'product.selectSize': 'Velg størrelse',
    'product.selectColor': 'Velg farge',
    'product.selectSizeAndColor': 'Velg størrelse og farge',
    'product.chooseVariant': 'Velg din variant',
    'common.share': 'Del',
    'common.each': 'hver',
    // About page specific translations
    'about.hero.title': 'Vores Historie',
    'about.hero.subtitle': 'En arv af autentisk nordisk håndværk der spænder over et århundrede',
    'about.timeline.title': 'Rejse Gennem Tid',
    'about.timeline.1892.title': 'Nordiske Traditioner Begynder',
    'about.timeline.1892.desc': 'Grundlagt i hjertet af Skandinavien begyndte vores håndværk med traditionel lærbearbejdningsteknikker videregviet gennem generationer.',
    'about.timeline.1950.title': 'Håndværkers Arv',
    'about.timeline.1950.desc': 'Tre generationer af mesterhåndværkere forfynede vores teknikker og etablerede kvalitetsstandarderne der definerer vores brand i dag.',
    'about.timeline.1985.title': 'Bæredygtig Innovation',
    'about.timeline.1985.desc': 'Vi var pionerer inden for miljøvennlige lærbearbejdningsmetoder og blev det første nordiske brand til at opnå kulstofneutral produktion.',
    'about.timeline.2020.title': 'Moderne Ekspertise',
    'about.timeline.2020.desc': 'I dag blander vi traditionelt håndværk med moderne design for at skabe tidløse stykker til den moderne nordiske livsstil.',
    'about.values.title': 'Vores Værdier',
    'about.values.heritage.title': 'Nordisk Arv',
    'about.values.heritage.desc': 'Forankret i skandinaviske traditioner og tidstestede håndværksteknikker.',
    'about.values.sustainability.title': 'Bæredygtighed',
    'about.values.sustainability.desc': 'Forpligtet til miljøansvar og etiske indkøbspraksis.',
    'about.values.quality.title': 'Kvalitet',
    'about.values.quality.desc': 'Kompromisløse standarder der sikrer at hvert stykke holder i generationer.',
    'about.timeline.established': 'Grundlagt',
    // Error pages
    'error.404.title': 'Side Ikke Fundet',
    'error.404.desc': 'Siden du leder efter findes ikke eller er blevet flyttet.',
    'error.404.goHome': 'Gå til Hjem',
    'error.404.goBack': 'Gå Tilbage',
    // Error pages
    'error.notFoundTitle': 'Siden blev ikke fundet',
    'error.notFoundDesc': 'Siden du leter efter eksisterer ikke eller har blevet flyttet.',
    'error.goHome': 'Gå til startsiden',
    'error.goBack': 'Gå tilbage'
  },
  fi: {
    'nav.home': 'Koti',
    'nav.products': 'Tuotteet',
    'nav.about': 'Meistä',
    'nav.contact': 'Yhteystiedot',
    'nav.admin': 'Admin',
    'nav.cart': 'Ostoskori',
    'nav.categories': 'Kategoriat',
    'nav.settings': 'Asetukset',
    'nav.wishlist': 'Toivelista',
    'nav.menu': 'Valikko',
    'nav.customer': 'Asiakas',
    'categories.bags': 'Laukut',
    'categories.wallets': 'Lompakot',
    'categories.belts': 'Vyöt',
    'categories.jackets': 'Takit',
    'categories.accessories': 'Lisävarusteet',
    'search.placeholder': 'Etsi tuotteita...',
    'search.title': 'Etsi Tuotteita',
    'promo.freeShipping': 'Ilmainen toimitus yli €100 tilauksille',
    'promo.support': '24/7 Asiakastuki',
    'theme.light': 'Vaalea tila',
    'theme.dark': 'Tumma tila',
    'hero.title': 'Premium Nahkatuotteet',
    'hero.subtitle': 'Käsintehty pohjoismaisen perinteen ja ajattoman tyylin mukaan',
    'hero.cta': 'Osta Kokoelma',
    'hero.authentic': 'Aito Pohjoismainen Käsityö',
    'hero.from': 'Skandinavian Sydämestä',
    'hero.description': 'Vuosisatojen vanhoilla tekniikoilla käsintehty, nahkatuotteemme ruumiillistavat pohjoismaisen laadun, kestävyyden ja ajattoman muotoilun hengen.',
    'hero.explore': 'Tutustu Kokoelmaan',
    'hero.story': 'Meidän Tarinamme',
    'products.title': 'Kokoelmamme',
    'products.filter': 'Suodata Kategorian mukaan',
    'products.all': 'Kaikki Tuotteet',
    'products.bags': 'Laukut',
    'products.wallets': 'Lompakot',
    'products.belts': 'Vyöt',
    'products.jackets': 'Takit',
    'products.accessories': 'Lisävarusteet',
    'product.addToCart': 'Lisää Koriin',
    'product.price': 'Hinta',
    'product.size': 'Koko',
    'product.color': 'Väri',
    'admin.title': 'Admin Paneeli',
    'admin.products': 'Hallitse Tuotteita',
    'admin.orders': 'Tilaukset',
    'admin.customers': 'Asiakkaat',
    'cart.title': 'Ostoskori',
    'cart.empty': 'Ostoskorisi on tyhjä',
    'cart.total': 'Yhteensä',
    'cart.checkout': 'Kassalle',
    'about.title': 'Tietoa Nordic Skinistä',
    'about.subtitle': 'Luomme premium nahkatuotteita pohjoismaisella perinteellä ja ajattomalla elegansilla vuodesta 1952.',
    'about.story': 'Tarinmme',
    'about.story.p1': 'Tukholman sydämessä perustettu Nordic Skin aloitti pienenä perhepajana, joka oli omistautunut säilyttämään vanhan nahkakäsityön taiteen. Perustajamme Erik Andersson uskoi, että todellinen laatu tulee kärsivällisyydestä, taidosta ja luonnonmateriaalien kunnioituksesta.',
    'about.story.p2': 'Nykyään jatkamme tätä perinnettä yhdistämällä ajan testaamia tekniikoita moderniin suunnitteluun luodaksemme nahkatuotteita, jotka kertovat tarinan pohjoismaisesta perinnöstä ja poikkeuksellisesta laadusta.',
    'about.values': 'Arvomme',
    'about.heritage': 'Pohjoismainen Perintö',
    'about.heritage.desc': 'Juurtunut skandinaaviseen perinteeseen ja käsityötaitoon',
    'about.sustainability': 'Kestävyys',
    'about.sustainability.desc': 'Eettinen hankinta ja ympäristötietoiset käytännöt',
    'about.quality': 'Laatu',
    'about.quality.desc': 'Huolellinen huomio yksityiskohtiin jokaisessa kappaleessa',
    'contact.title': 'Ota Yhteyttä',
    'contact.subtitle': 'Onko sinulla kysymys tai haluatko tietää lisää käsintehdyistä pohjoismaisista nahkatuotteistamme? Haluaisimme kuulla sinusta.',
    'contact.form.name': 'Koko Nimi',
    'contact.form.email': 'Sähköpostiosoite',
    'contact.form.subject': 'Aihe',
    'contact.form.message': 'Viesti',
    'contact.form.send': 'Lähetä Viesti',
    'contact.info': 'Yhteystiedot',
    'contact.address': 'Osoite',
    'contact.phone': 'Puhelin',
    'contact.email': 'Sähköposti',
    'contact.hours': 'Aukioloajat',
    'footer.brand.desc': 'Käsintehtyjä nahkatuotteita pohjoismaisella perinteellä ja ajattomalla tyylillä.',
    'footer.quicklinks': 'Pikalinkit',
    'footer.categories': 'Kategoriat',
    'footer.contact': 'Yhteystiedot',
    'footer.company': 'Nordic Skin Co.',
    'footer.location': 'Tukholma, Ruotsi',
    'footer.copyright': '© 2024 Nordic Skin. Kaikki oikeudet pidätetään.',
    'footer.privacy': 'Tietosuojakäytäntö',
    'footer.terms': 'Käyttöehdot',
    'common.featured': 'Esiteltyjä Kokoelma',
    'common.new': 'Uusi',
    'common.viewDetails': 'Katso Tiedot',
    'common.discover': 'Tutustu kokoelmaamme käsintehtyjä nahkatuotteita, joista jokainen kertoo oman tarinansa pohjoismaisesta perinteestä.',
    'auth.login': 'Kirjaudu sisään',
    'auth.signup': 'Rekisteröidy',
    'auth.logout': 'Kirjaudu ulos',
    'auth.loginGoogle': 'Jatka Googlella',
    'auth.loginCustomer': 'Asiakaskirjautuminen',
    'auth.loginAdmin': 'Ylläpitokirjautuminen',
    'auth.email': 'Sähköposti',
    'auth.password': 'Salasana',
    'auth.confirmPassword': 'Vahvista Salasana',
    'auth.name': 'Nimi',
    'auth.createAccount': 'Luo Tili',
    'auth.haveAccount': 'Onko sinulla jo tili?',
    'auth.noAccount': 'Ei tiliä?',
    'auth.profile': 'Profiili',
    'auth.updateProfile': 'Päivitä Profiili',
    'auth.saveChanges': 'Tallenna Muutokset',
    'auth.loading': 'Ladataan tiliä...',
    'toast.loginSuccess': 'Kirjautuminen onnistui!',
    'toast.signupSuccess': 'Tili luotu onnistuneesti!',
    'toast.logoutSuccess': 'Uloskirjautuminen onnistui!',
    'toast.profileUpdated': 'Profiili päivitetty onnistuneesti!',
    'toast.cartUpdated': 'Ostoskori päivitetty onnistuneesti!',
    'toast.addedToCart': 'Lisätty ostoskoriin!',
    'toast.error': 'Tapahtui virhe. Yritä uudelleen.',
    'toast.loginError': 'Kirjautuminen epäonnistui. Tarkista tietosi.',
    'toast.signupError': 'Rekisteröityminen epäonnistui. Yritä uudelleen.',
    'toast.cartError': 'Ostoskorin päivitys epäonnistui.',
    'error.unauthorized': 'Luvaton pääsy',
    'error.notFound': 'Sivua ei löytynyt',
    'error.serverError': 'Palvelinvirhe',
    'error.networkError': 'Verkkovirhe',
    'error.validationError': 'Validointivirhe',
    'error.generic': 'Jotain meni pieleen',
    'cart.quantity': 'Määrä',
    'cart.remove': 'Poista',
    'cart.update': 'Päivitä',
    'cart.subtotal': 'Välisumma',
    'cart.shipping': 'Toimitus',
    'cart.tax': 'Vero',
    'cart.loading': 'Ladataan...',
    'cart.continue': 'Jatka Ostoksia',
    'common.loading': 'Ladataan...',
    'common.save': 'Tallenna',
    'common.cancel': 'Peruuta',
    'common.delete': 'Poista',
    'common.edit': 'Muokkaa',
    'common.close': 'Sulje',
    'common.yes': 'Kyllä',
    'common.no': 'Ei',
    'common.none': 'Ei mitään',
    'common.ok': 'OK',
    'common.back': 'Takaisin',
    'common.next': 'Seuraava',
    'common.previous': 'Edellinen',
    'admin.dashboard': 'Hallintapaneeli',
    'admin.addProduct': 'Lisää Tuote',
    'admin.editProduct': 'Muokkaa Tuote',
    'admin.deleteProduct': 'Poista Tuote',
    'admin.manageUsers': 'Hallitse Käyttäjiä',
    'address.title': 'Osoitteet',
    'address.add': 'Lisää Osoite',
    'address.edit': 'Muokkaa Osoitetta',
    'address.delete': 'Poista Osoite',
    'address.setDefault': 'Aseta Oletukseksi',
    'address.default': 'Oletus',
    'address.type': 'Osoitetyyppi',
    'address.home': 'Koti',
    'address.work': 'Työ',
    'address.other': 'Muu',
    'address.label': 'Nimike',
    'address.street': 'Katuosoite',
    'address.city': 'Kaupunki',
    'address.state': 'Maakunta/Provinssi',
    'address.postalCode': 'Postinumero',
    'address.country': 'Maa',
    'address.save': 'Tallenna Osoite',
    'address.cancel': 'Peruuta',
    'address.confirmDelete': 'Oletko varma, että haluat poistaa tämän osoitteen?',
    'address.mustHaveOne': 'Sinulla täytyy olla vähintään yksi osoite',
    'address.addSuccess': 'Osoite lisätty onnistuneesti!',
    'address.updateSuccess': 'Osoite päivitetty onnistuneesti!',
    'address.deleteSuccess': 'Osoite poistettu onnistuneesti!',
    'address.defaultSuccess': 'Oletusosoite päivitetty!',
    'admin.settings': 'Asetukset',
    'admin.reports': 'Raportit',
    'product.details': 'Tuotetiedot',
    'product.description': 'Kuvaus',
    'product.specifications': 'Tekniset tiedot',
    'product.reviews': 'Arvostelut',
    'product.inStock': 'Varastossa',
    'product.outOfStock': 'Loppuunmyyty',
    'product.selectSize': 'Valitse koko',
    'product.selectColor': 'Valitse väri',
    'product.selectSizeAndColor': 'Valitse koko ja väri',
    'product.chooseVariant': 'Valitse variantti',
    'common.share': 'Jaa',
    'common.each': 'kpl',
    // About page specific translations
    'about.hero.title': 'Meidän Tarinamme',
    'about.hero.subtitle': 'Aidon pohjoismaisen käsityön perintö, joka ulottuu yli vuosisadan ajan',
    'about.timeline.title': 'Matka Ajan Halki',
    'about.timeline.1892.title': 'Pohjoismaiset Perinteet Alkavat',
    'about.timeline.1892.desc': 'Skandinavian sydämessä perustettu käsityömme alkoi perinteisillä nahankäsittelytekniikoilla, jotka on siirretty sukupolvelta toiselle.',
    'about.timeline.1950.title': 'Käsityöläisten Perintö',
    'about.timeline.1950.desc': 'Kolme sukupolvea mestärikäsityöläisiä jalosti tekniikoitamme ja loi laatustandardit, jotka määrittelevät brändimme tänään.',
    'about.timeline.1985.title': 'Kestävä Innovaatio',
    'about.timeline.1985.desc': 'Olimme edelläkävijöitä ympäristöystävällisissä nahankäsittelymenetelmissä ja tulimme ensimmäiseksi pohjoismaiseksi brändiksi, joka saavutti hiilineutraalin tuotannon.',
    'about.timeline.2020.title': 'Moderni Huippuosaaminen',
    'about.timeline.2020.desc': 'Nykyään yhdistämme perinteistä käsityötä moderniin muotoiluun luodaksemme ajattomia kappaleita nykyaikaiseen pohjoismaiseen elämäntapaan.',
    'about.values.title': 'Arvomme',
    'about.values.heritage.title': 'Pohjoismainen Perintö',
    'about.values.heritage.desc': 'Juuremme skandinaavisissa perinteissä ja aikojen testatuissa käsityötekniikoissa.',
    'about.values.sustainability.title': 'Kestävyys',
    'about.values.sustainability.desc': 'Sitoutuneita ympäristövastuuseen ja eettisiin hankintakäytäntöihin.',
    'about.values.quality.title': 'Laatu',
    'about.values.quality.desc': 'Kompromissittomat standardit varmistavat, että jokainen kappale kestää sukupolvia.',
    'about.timeline.established': 'Perustettu',
    // Error pages
    'error.404.title': 'Sivua Ei Löydy',
    'error.404.desc': 'Etsimääsi sivua ei ole olemassa tai se on siirretty.',
    'error.404.goHome': 'Siirry Etusivulle',
    'error.404.goBack': 'Palaa Takaisin',
    // Error pages
    'error.notFoundTitle': 'Meidän Tarinamme',
    'error.notFoundDesc': 'Aidon pohjoismaisen käsityön perintö, joka ulottuu yli vuosisadan ajan',
    'error.goHome': 'Siirry etusivulle',
    'error.goBack': 'Palaa takaisin'
  },
  is: {
    'nav.home': 'Heim',
    'nav.products': 'Vörur',
    'nav.about': 'Um okkur',
    'nav.contact': 'Samband',
    'nav.admin': 'Stjórnandi',
    'nav.cart': 'Karfa',
    'nav.categories': 'Flokkar',
    'nav.settings': 'Stillingar',
    'nav.wishlist': 'Óskalistí',
    'nav.menu': 'Valmynd',
    'nav.customer': 'Viðskiptavinur',
    'categories.bags': 'Töskur',
    'categories.wallets': 'Veski',
    'categories.belts': 'Belti',
    'categories.jackets': 'Jakkar',
    'categories.accessories': 'Fylgihlutir',
    'search.placeholder': 'Leita að vörum...',
    'search.title': 'Leita Vörur',
    'promo.freeShipping': 'Ókeypis sending á pantanir yfir €100',
    'promo.support': '24/7 Þjónustuver',
    'theme.light': 'Ljós ham',
    'theme.dark': 'Dökk ham',
    'hero.title': 'Úrvals Leðurvörur',
    'hero.subtitle': 'Handgerðar með norrænum hefðum og tímalausum stíl',
    'hero.cta': 'Kaupa Safn',
    'hero.authentic': 'Ekta Norræn Handverk',
    'hero.from': 'Frá Hjarta Skandinavíu',
    'hero.description': 'Handgerðar með aldalöngum tækni, leðurvörur okkar líkama norræna anda gæða, endingu og tímalausrar hönnunar.',
    'hero.explore': 'Kanna Safn',
    'hero.story': 'Sagan Okkar',
    'products.title': 'Safnið Okkar',
    'products.filter': 'Sía eftir Flokki',
    'products.all': 'Allar Vörur',
    'products.bags': 'Töskur',
    'products.wallets': 'Veski',
    'products.belts': 'Belti',
    'products.jackets': 'Jakkar',
    'products.accessories': 'Fylgihlutir',
    'product.addToCart': 'Bæta í Körfu',
    'product.price': 'Verð',
    'product.size': 'Stærð',
    'product.color': 'Litur',
    'admin.title': 'Stjórnborð',
    'admin.products': 'Stjórna Vörum',
    'admin.orders': 'Pantanir',
    'admin.customers': 'Viðskiptavinir',
    'cart.title': 'Innkaupakörfu',
    'cart.empty': 'Körfan þín er tóm',
    'cart.total': 'Samtals',
    'cart.checkout': 'Til greiðslu',
    'about.title': 'Um Nordic Skin',
    'about.subtitle': 'Búa til úrvals leðurvörur með norrænum hefðum og tímalausri glæsileika síðan 1952.',
    'about.story': 'Saga Okkar',
    'about.story.p1': 'Stofnað í hjarta Stokkhólms, Nordic Skin byrjaði sem lítil fjölskylduverkstæði tileinkuð því að varðveita fornleikinn á leðursmíði. Stofnandi okkar, Erik Andersson, trúði því að raunveruleg gæði komi frá þolinmæði, færni og virðingu fyrir náttúrulegum efnum.',
    'about.story.p2': 'Í dag höldum við þessari hefð áfram og sameinum gamalgrónar aðferðir við nútímalega hönnun til að búa til leðurvörur sem segja sögu af norrænum arfi og óvenjulegum gæðum.',
    'about.values': 'Gildi Okkar',
    'about.heritage': 'Norrænn Arfur',
    'about.heritage.desc': 'Rótgróið í skandinavískum hefðum og handverki',
    'about.sustainability': 'Sjálfbærni',
    'about.sustainability.desc': 'Siðferðileg innkaup og umhverfisvænar aðferðir',
    'about.quality': 'Gæði',
    'about.quality.desc': 'Vandlega athygli á smáatriðum í hverju stykki',
    'contact.title': 'Hafðu Samband',
    'contact.subtitle': 'Áttu spurningu eða vilt læra meira um handgerðar norrænar leðurvörur okkar? Við myndum elska að heyra frá þér.',
    'contact.form.name': 'Fullt Nafn',
    'contact.form.email': 'Netfang',
    'contact.form.subject': 'Efni',
    'contact.form.message': 'Skilaboð',
    'contact.form.send': 'Senda Skilaboð',
    'contact.info': 'Sambandsupplýsingar',
    'contact.address': 'Heimilisfang',
    'contact.phone': 'Sími',
    'contact.email': 'Netfang',
    'contact.hours': 'Opnunartímar',
    'footer.brand.desc': 'Handgerðar leðurvörur með norrænum hefðum og tímalausum stíl.',
    'footer.quicklinks': 'Flýtileiðir',
    'footer.categories': 'Flokkar',
    'footer.contact': 'Samband',
    'footer.company': 'Nordic Skin Co.',
    'footer.location': 'Stokkhólmur, Svíþjóð',
    'footer.copyright': '© 2024 Nordic Skin. Allur réttur áskilinn.',
    'footer.privacy': 'Persónuverndarstefna',
    'footer.terms': 'Þjónustuskilmálar',
    'common.featured': 'Úrvals Safn',
    'common.new': 'Nýtt',
    'common.viewDetails': 'Skoða Upplýsingar',
    'common.discover': 'Uppgötvaðu safn okkar af handgerðum leðurvörum, hvert stykki segir sína eigin sögu af norrænum hefðum.',
    'auth.login': 'Innskrá',
    'auth.signup': 'Skrá sig',
    'auth.logout': 'Útskrá',
    'auth.loginGoogle': 'Halda áfram með Google',
    'auth.loginCustomer': 'Viðskiptavinur Innskrá',
    'auth.loginAdmin': 'Stjórnandi Innskrá',
    'auth.email': 'Netfang',
    'auth.password': 'Lykilorð',
    'auth.confirmPassword': 'Staðfesta Lykilorð',
    'auth.name': 'Nafn',
    'auth.createAccount': 'Búa til Reikning',
    'auth.haveAccount': 'Áttu þegar reikning?',
    'auth.noAccount': 'Engan reikning?',
    'auth.profile': 'Snið',
    'auth.updateProfile': 'Uppfæra Snið',
    'auth.saveChanges': 'Vista Breytingar',
    'auth.loading': 'Hleður reikningi...',
    'toast.loginSuccess': 'Innskráning tókst!',
    'toast.signupSuccess': 'Reikningur búinn til!',
    'toast.logoutSuccess': 'Útskráning tókst!',
    'toast.profileUpdated': 'Snið uppfært!',
    'toast.cartUpdated': 'Karfa uppfærð!',
    'toast.addedToCart': 'Bætt í körfu!',
    'toast.error': 'Villa kom upp. Reyndu aftur.',
    'toast.loginError': 'Innskráning mistókst. Athugaðu upplýsingar.',
    'toast.signupError': 'Skráning mistókst. Reyndu aftur.',
    'toast.cartError': 'Tókst ekki að uppfæra körfu.',
    'error.unauthorized': 'Óheimil aðgangur',
    'error.notFound': 'Síða fannst ekki',
    'error.serverError': 'Miðlaravilla',
    'error.networkError': 'Netkerfsvilla',
    'error.validationError': 'Staðfestingarvilla',
    'error.generic': 'Eitthvað fór úrskeiðis',
    'cart.quantity': 'Magn',
    'cart.remove': 'Fjarlægja',
    'cart.update': 'Uppfæra',
    'cart.subtotal': 'Hlutasamtala',
    'cart.shipping': 'Sending',
    'cart.tax': 'Skattur',
    'cart.loading': 'Hleður...',
    'cart.continue': 'Halda áfram að Versla',
    'common.loading': 'Hleður...',
    'common.save': 'Vista',
    'common.cancel': 'Hætta við',
    'common.delete': 'Eyða',
    'common.edit': 'Breyta',
    'common.close': 'Loka',
    'common.yes': 'Já',
    'common.no': 'Nei',
    'common.none': 'Ekkert',
    'common.ok': 'Í lagi',
    'common.back': 'Til baka',
    'common.next': 'Næsta',
    'common.previous': 'Fyrri',
    'admin.dashboard': 'Stjórnborð',
    'admin.addProduct': 'Bæta við Vöru',
    'admin.editProduct': 'Breyta Vöru',
    'admin.deleteProduct': 'Eyða Vöru',
    'admin.manageUsers': 'Stjórna Notendum',
    'address.title': 'Heimilisföng',
    'address.add': 'Bæta við Heimilisfangi',
    'address.edit': 'Breyta Heimilisfangi',
    'address.delete': 'Eyða Heimilisfangi',
    'address.setDefault': 'Setja sem Sjálfgefið',
    'address.default': 'Sjálfgefið',
    'address.type': 'Tegund Heimilisfangs',
    'address.home': 'Heimili',
    'address.work': 'Vinna',
    'address.other': 'Annað',
    'address.label': 'Merki',
    'address.street': 'Götuheiti',
    'address.city': 'Borg',
    'address.state': 'Hérað/Fylki',
    'address.postalCode': 'Póstnúmer',
    'address.country': 'Land',
    'address.save': 'Vista Heimilisfang',
    'address.cancel': 'Hætta við',
    'address.confirmDelete': 'Ertu viss um að þú viljir eyða þessu heimilisfangi?',
    'address.mustHaveOne': 'Þú verður að hafa að minnsta kosti eitt heimilisfang',
    'address.addSuccess': 'Heimilisfangi bætt við!',
    'address.updateSuccess': 'Heimilisfang uppfært!',
    'address.deleteSuccess': 'Heimilisfangi eytt!',
    'address.defaultSuccess': 'Sjálfgefið heimilisfang uppfært!',
    'admin.settings': 'Stillingar',
    'admin.reports': 'Skýrslur',
    'product.details': 'Vöruupplýsingar',
    'product.description': 'Lýsing',
    'product.specifications': 'Forskriftir',
    'product.reviews': 'Umsagnir',
    'product.inStock': 'Til á lager',
    'product.outOfStock': 'Uppselt',
    'product.selectSize': 'Velja stærð',
    'product.selectColor': 'Velja lit',
    'product.selectSizeAndColor': 'Veldu stærð og lit',
    'product.chooseVariant': 'Veldu afbrigði',
    'common.share': 'Deila',
    'common.each': 'hvör',
    // About page specific translations
    'about.hero.title': 'Saga Okkar',
    'about.hero.subtitle': 'Arfleifð af ekta norrænu handverki sem nær yfir heila öld',
    'about.timeline.title': 'Ferð Í Gegnum Tímann',
    'about.timeline.1892.title': 'Norrænar Hefðir Hefjast',
    'about.timeline.1892.desc': 'Stofnað í hjarta Skandinavíu byrjaði handverk okkar með hefðbundnum leðursmíðitækni sem var afhent í gegnum kynslóðir.',
    'about.timeline.1950.title': 'Arfleifð Handverksmanna',
    'about.timeline.1950.desc': 'Þrjár kynslóðir meistara handverksmanna fínstilltu tækni okkar og stofnuðu gæðastaðla sem skilgreina vörumerki okkar í dag.',
    'about.timeline.1985.title': 'Sjálfbær Nýsköpun',
    'about.timeline.1985.desc': 'Við vorum frumkvöðlar í umhverfisvænum leðursmíðiaðferðum og urðum fyrsta norræna vörumerkið til að ná kolefnishlutlausri framleiðslu.',
    'about.timeline.2020.title': 'Nútíma Framúrskarandi',
    'about.timeline.2020.desc': 'Í dag blöndum við hefðbundnu handverki við nútíma hönnun til að búa til tímalaus stykki fyrir nútíma norræna lífsstíl.',
    'about.values.title': 'Gildi Okkar',
    'about.values.heritage.title': 'Norræn Arfleifð',
    'about.values.heritage.desc': 'Rótgróið í skandinavískum hefðum og tímareyndum handverkstækni.',
    'about.values.sustainability.title': 'Sjálfbærni',
    'about.values.sustainability.desc': 'Skuldbundið til umhverfisábyrgðar og siðlegra innkaupavenja.',
    'about.values.quality.title': 'Gæði',
    'about.values.quality.desc': 'Málaðlausir staðlar sem tryggja að hvert stykki endist í kynslóðir.',
    'about.timeline.established': 'Stofnað',
    // Error pages
    'error.404.title': 'Síða Fannst Ekki',
    'error.404.desc': 'Síðan sem þú leitar að er ekki til eða hefur verið færð.',
    'error.404.goHome': 'Fara Heim',
    'error.404.goBack': 'Fara Til Baka',
    // Error pages
    'error.notFoundTitle': 'Ferð Í Gegnum Tímann',
    'error.notFoundDesc': 'Eitt af því sem við köllum fortíðin, nútíðin eða framtíðin. Við skulum finna réttu leiðina aftur.',
    'error.goHome': 'Farðu á forsíðu',
    'error.goBack': 'Farðu til baka'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const currentTranslations = translations[language];
    const fallbackTranslations = translations['en'];
    
    // First try to get the translation in the current language
    if (currentTranslations && currentTranslations[key as keyof typeof currentTranslations]) {
      return currentTranslations[key as keyof typeof currentTranslations];
    }
    
    // If not found, try the English translation
    if (fallbackTranslations && fallbackTranslations[key as keyof typeof fallbackTranslations]) {
      return fallbackTranslations[key as keyof typeof fallbackTranslations];
    }
    
    // If still not found, return the key itself as a fallback
    console.warn(`Translation key not found: ${key}`);
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};