import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'sv' | 'no' | 'da' | 'fi' | 'is';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.cart': 'Cart',
    'nav.categories': 'Categories',
    'nav.settings': 'Settings',
    'nav.wishlist': 'Wishlist',
    'categories.bags': 'Bags',
    'categories.wallets': 'Wallets',
    'categories.belts': 'Belts',
    'categories.jackets': 'Jackets',
    'categories.accessories': 'Accessories',
    'search.placeholder': 'Search for products...',
    'search.title': 'Search Products',
    'promo.freeShipping': 'Free Shipping on Orders Over €100',
    'promo.support': '24/7 Customer Support',
    'theme.light': 'Light Mode',
    'theme.dark': 'Dark Mode',
    'hero.title': 'Premium Leather Goods',
    'hero.subtitle': 'Handcrafted with Nordic tradition and timeless style',
    'hero.cta': 'Shop Collection',
    'products.title': 'Our Collection',
    'products.filter': 'Filter by Category',
    'products.all': 'All Products',
    'products.bags': 'Bags',
    'products.wallets': 'Wallets',
    'products.belts': 'Belts',
    'products.jackets': 'Jackets',
    'products.accessories': 'Accessories',
    'product.addToCart': 'Add to Cart',
    'product.price': 'Price',
    'product.size': 'Size',
    'product.color': 'Color',
    'admin.title': 'Admin Dashboard',
    'admin.products': 'Manage Products',
    'admin.orders': 'Orders',
    'admin.customers': 'Customers',
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'about.title': 'About Nordic Leather',
    'about.subtitle': 'Crafting premium leather goods with Nordic tradition and timeless elegance since 1952.',
    'about.story': 'Our Story',
    'about.story.p1': 'Founded in the heart of Stockholm, Nordic Leather began as a small family workshop dedicated to preserving the ancient art of leather craftsmanship. Our founder, Erik Andersson, believed that true quality comes from patience, skill, and respect for natural materials.',
    'about.story.p2': 'Today, we continue this tradition, combining time-honored techniques with modern design to create leather goods that tell a story of Nordic heritage and exceptional quality.',
    'about.values': 'Our Values',
    'about.heritage': 'Nordic Heritage',
    'about.heritage.desc': 'Rooted in Scandinavian tradition and craftsmanship',
    'about.sustainability': 'Sustainability',
    'about.sustainability.desc': 'Ethical sourcing and environmentally conscious practices',
    'about.quality': 'Quality',
    'about.quality.desc': 'Meticulous attention to detail in every piece',
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Have a question or want to learn more about our handcrafted Nordic leather goods? We\'d love to hear from you.',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.info': 'Contact Information',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.hours': 'Business Hours',
    'footer.brand.desc': 'Handcrafted leather goods with Nordic tradition and timeless style.',
    'footer.quicklinks': 'Quick Links',
    'footer.categories': 'Categories',
    'footer.contact': 'Contact',
    'footer.company': 'Nordic Leather Co.',
    'footer.location': 'Stockholm, Sweden',
    'footer.copyright': '© 2024 Nordic Leather. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'common.featured': 'Featured Collection',
    'common.new': 'New',
    'common.viewDetails': 'View Details',
    'common.discover': 'Discover our collection of handcrafted leather goods, each piece telling its own story of Nordic tradition.'
  },
  sv: {
    'nav.home': 'Hem',
    'nav.products': 'Produkter',
    'nav.about': 'Om oss',
    'nav.contact': 'Kontakt',
    'nav.admin': 'Admin',
    'nav.cart': 'Kundvagn',
    'nav.categories': 'Kategorier',
    'nav.settings': 'Inställningar',
    'nav.wishlist': 'Önskelista',
    'categories.bags': 'Väskor',
    'categories.wallets': 'Plånböcker',
    'categories.belts': 'Bälten',
    'categories.jackets': 'Jackor',
    'categories.accessories': 'Tillbehör',
    'search.placeholder': 'Sök efter produkter...',
    'search.title': 'Sök Produkter',
    'promo.freeShipping': 'Fri frakt på beställningar över €100',
    'promo.support': '24/7 Kundsupport',
    'theme.light': 'Ljust läge',
    'theme.dark': 'Mörkt läge',
    'hero.title': 'Högkvalitativa Lädervaror',
    'hero.subtitle': 'Handgjorda med nordisk tradition och tidlös stil',
    'hero.cta': 'Handla Kollektion',
    'products.title': 'Vår Kollektion',
    'products.filter': 'Filtrera efter Kategori',
    'products.all': 'Alla Produkter',
    'products.bags': 'Väskor',
    'products.wallets': 'Plånböcker',
    'products.belts': 'Bälten',
    'products.jackets': 'Jackor',
    'products.accessories': 'Tillbehör',
    'product.addToCart': 'Lägg i Kundvagn',
    'product.price': 'Pris',
    'product.size': 'Storlek',
    'product.color': 'Färg',
    'admin.title': 'Admin Panel',
    'admin.products': 'Hantera Produkter',
    'admin.orders': 'Beställningar',
    'admin.customers': 'Kunder',
    'cart.title': 'Kundvagn',
    'cart.empty': 'Din kundvagn är tom',
    'cart.total': 'Totalt',
    'cart.checkout': 'Checkout',
    'about.title': 'Om Nordic Leather',
    'about.subtitle': 'Skapar förstklassiga lädervaror med nordisk tradition och tidlös elegans sedan 1952.',
    'about.story': 'Vår Historia',
    'about.story.p1': 'Grundat i hjärtat av Stockholm började Nordic Leather som en liten familjeverkstad dedikerad till att bevara den gamla konsten av läderhantverk. Vår grundare, Erik Andersson, trodde att verklig kvalitet kommer från tålamod, skicklighet och respekt för naturliga material.',
    'about.story.p2': 'Idag fortsätter vi denna tradition och kombinerar tidstestade tekniker med modern design för att skapa lädervaror som berättar en historia om nordiskt arv och exceptionell kvalitet.',
    'about.values': 'Våra Värderingar',
    'about.heritage': 'Nordiskt Arv',
    'about.heritage.desc': 'Rotad i skandinavisk tradition och hantverk',
    'about.sustainability': 'Hållbarhet',
    'about.sustainability.desc': 'Etisk inköp och miljömedvetna metoder',
    'about.quality': 'Kvalitet',
    'about.quality.desc': 'Noggrann uppmärksamhet på detaljer i varje stycke',
    'contact.title': 'Kontakta Oss',
    'contact.subtitle': 'Har du en fråga eller vill veta mer om våra handgjorda nordiska lädervaror? Vi skulle gärna höra från dig.',
    'contact.form.name': 'Fullständigt Namn',
    'contact.form.email': 'E-postadress',
    'contact.form.subject': 'Ämne',
    'contact.form.message': 'Meddelande',
    'contact.form.send': 'Skicka Meddelande',
    'contact.info': 'Kontaktinformation',
    'contact.address': 'Adress',
    'contact.phone': 'Telefon',
    'contact.email': 'E-post',
    'contact.hours': 'Öppettider',
    'footer.brand.desc': 'Handgjorda lädervaror med nordisk tradition och tidlös stil.',
    'footer.quicklinks': 'Snabblänkar',
    'footer.categories': 'Kategorier',
    'footer.contact': 'Kontakt',
    'footer.company': 'Nordic Leather Co.',
    'footer.location': 'Stockholm, Sverige',
    'footer.copyright': '© 2024 Nordic Leather. Alla rättigheter förbehållna.',
    'footer.privacy': 'Sekretesspolicy',
    'footer.terms': 'Användarvillkor',
    'common.featured': 'Utvald Kollektion',
    'common.new': 'Ny',
    'common.viewDetails': 'Visa Detaljer',
    'common.discover': 'Upptäck vår kollektion av handgjorda lädervaror, varje stycke berättar sin egen historia om nordisk tradition.'
  },
  no: {
    'nav.home': 'Hjem',
    'nav.products': 'Produkter',
    'nav.about': 'Om oss',
    'nav.contact': 'Kontakt',
    'nav.admin': 'Admin',
    'nav.cart': 'Handlekurv',
    'nav.categories': 'Kategorier',
    'nav.settings': 'Innstillinger',
    'nav.wishlist': 'Ønskeliste',
    'categories.bags': 'Vesker',
    'categories.wallets': 'Lommebøker',
    'categories.belts': 'Belter',
    'categories.jackets': 'Jakker',
    'categories.accessories': 'Tilbehør',
    'search.placeholder': 'Søk etter produkter...',
    'search.title': 'Søk Produkter',
    'promo.freeShipping': 'Gratis frakt på bestillinger over €100',
    'promo.support': '24/7 Kundestøtte',
    'theme.light': 'Lys modus',
    'theme.dark': 'Mørk modus',
    'hero.title': 'Premium Lærvarer',
    'hero.subtitle': 'Håndlaget med nordisk tradisjon og tidløs stil',
    'hero.cta': 'Handle Kolleksjon',
    'products.title': 'Vår Kolleksjon',
    'products.filter': 'Filtrer etter Kategori',
    'products.all': 'Alle Produkter',
    'products.bags': 'Vesker',
    'products.wallets': 'Lommebøker',
    'products.belts': 'Belter',
    'products.jackets': 'Jakker',
    'products.accessories': 'Tilbehør',
    'product.addToCart': 'Legg i Handlekurv',
    'product.price': 'Pris',
    'product.size': 'Størrelse',
    'product.color': 'Farge',
    'admin.title': 'Admin Panel',
    'admin.products': 'Administrer Produkter',
    'admin.orders': 'Bestillinger',
    'admin.customers': 'Kunder',
    'cart.title': 'Handlekurv',
    'cart.empty': 'Handlekurven din er tom',
    'cart.total': 'Totalt',
    'cart.checkout': 'Til kassen',
    'about.title': 'Om Nordic Leather',
    'about.subtitle': 'Lager premium lærvarer med nordisk tradisjon og tidløs eleganse siden 1952.',
    'about.story': 'Vår Historie',
    'about.story.p1': 'Grunnlagt i hjertet av Stockholm begynte Nordic Leather som en liten familieverksted dedikert til å bevare den gamle kunsten av lærhåndverk. Vår grunnlegger, Erik Andersson, trodde at ekte kvalitet kommer fra tålmodighet, ferdighet og respekt for naturlige materialer.',
    'about.story.p2': 'I dag fortsetter vi denne tradisjonen og kombinerer tidserprobde teknikker med moderne design for å lage lærvarer som forteller en historie om nordisk arv og eksepsjonell kvalitet.',
    'about.values': 'Våre Verdier',
    'about.heritage': 'Nordisk Arv',
    'about.heritage.desc': 'Forankret i skandinavisk tradisjon og håndverk',
    'about.sustainability': 'Bærekraft',
    'about.sustainability.desc': 'Etisk innkjøp og miljøbevisste praksiser',
    'about.quality': 'Kvalitet',
    'about.quality.desc': 'Grundig oppmerksomhet på detaljer i hvert stykke',
    'contact.title': 'Ta Kontakt',
    'contact.subtitle': 'Har du et spørsmål eller vil lære mer om våre håndlagede nordiske lærvarer? Vi vil gjerne høre fra deg.',
    'contact.form.name': 'Fullt Navn',
    'contact.form.email': 'E-postadresse',
    'contact.form.subject': 'Emne',
    'contact.form.message': 'Melding',
    'contact.form.send': 'Send Melding',
    'contact.info': 'Kontaktinformasjon',
    'contact.address': 'Adresse',
    'contact.phone': 'Telefon',
    'contact.email': 'E-post',
    'contact.hours': 'Åpningstider',
    'footer.brand.desc': 'Håndlagede lærvarer med nordisk tradisjon og tidløs stil.',
    'footer.quicklinks': 'Hurtiglenker',
    'footer.categories': 'Kategorier',
    'footer.contact': 'Kontakt',
    'footer.company': 'Nordic Leather Co.',
    'footer.location': 'Stockholm, Sverige',
    'footer.copyright': '© 2024 Nordic Leather. Alle rettigheter forbeholdt.',
    'footer.privacy': 'Personvernpolicy',
    'footer.terms': 'Vilkår for tjeneste',
    'common.featured': 'Utvalgt Samling',
    'common.new': 'Ny',
    'common.viewDetails': 'Se Detaljer',
    'common.discover': 'Oppdag vår samling av håndlagede lærvarer, hvert stykke forteller sin egen historie om nordisk tradisjon.'
  },
  da: {
    'nav.home': 'Hjem',
    'nav.products': 'Produkter',
    'nav.about': 'Om os',
    'nav.contact': 'Kontakt',
    'nav.admin': 'Admin',
    'nav.cart': 'Indkøbskurv',
    'nav.categories': 'Kategorier',
    'nav.settings': 'Indstillinger',
    'nav.wishlist': 'Ønskeliste',
    'categories.bags': 'Tasker',
    'categories.wallets': 'Tegnebøger',
    'categories.belts': 'Bælter',
    'categories.jackets': 'Jakker',
    'categories.accessories': 'Tilbehør',
    'search.placeholder': 'Søg efter produkter...',
    'search.title': 'Søg Produkter',
    'promo.freeShipping': 'Gratis fragt på bestillinger over €100',
    'promo.support': '24/7 Kundesupport',
    'theme.light': 'Lys tilstand',
    'theme.dark': 'Mørk tilstand',
    'hero.title': 'Premium Lædervarer',
    'hero.subtitle': 'Håndlavet med nordisk tradition og tidløs stil',
    'hero.cta': 'Shop Kollektion',
    'products.title': 'Vores Kollektion',
    'products.filter': 'Filtrer efter Kategori',
    'products.all': 'Alle Produkter',
    'products.bags': 'Tasker',
    'products.wallets': 'Tegnebøger',
    'products.belts': 'Bælter',
    'products.jackets': 'Jakker',
    'products.accessories': 'Tilbehør',
    'product.addToCart': 'Tilføj til Kurv',
    'product.price': 'Pris',
    'product.size': 'Størrelse',
    'product.color': 'Farve',
    'admin.title': 'Admin Panel',
    'admin.products': 'Administrer Produkter',
    'admin.orders': 'Ordrer',
    'admin.customers': 'Kunder',
    'cart.title': 'Indkøbskurv',
    'cart.empty': 'Din indkøbskurv er tom',
    'cart.total': 'I alt',
    'cart.checkout': 'Til betaling',
    'about.title': 'Om Nordic Leather',
    'about.subtitle': 'Skaber premium lædervarer med nordisk tradition og tidløs elegance siden 1952.',
    'about.story': 'Vores Historie',
    'about.story.p1': 'Grundlagt i hjertet af Stockholm begyndte Nordic Leather som et lille familieværksted dedikeret til at bevare den gamle kunst af læhåndværk. Vores grundlægger, Erik Andersson, troede på at ægte kvalitet kommer fra tålmodighed, færdighed og respekt for naturlige materialer.',
    'about.story.p2': 'I dag fortsætter vi denne tradition og kombinerer tidstestede teknikker med moderne design for at skabe lædervarer, der fortæller en historie om nordisk arv og exceptionel kvalitet.',
    'about.values': 'Vores Værdier',
    'about.heritage': 'Nordisk Arv',
    'about.heritage.desc': 'Rodfæstet i skandinavisk tradition og håndværk',
    'about.sustainability': 'Bæredygtighed',
    'about.sustainability.desc': 'Etisk indkøb og miljøbevidste praksisser',
    'about.quality': 'Kvalitet',
    'about.quality.desc': 'Omhyggelig opmærksomhed på detaljer i hvert stykke',
    'contact.title': 'Kontakt Os',
    'contact.subtitle': 'Har du et spørgsmål eller vil vide mere om vores håndlavede nordiske lædervarer? Vi vil gerne høre fra dig.',
    'contact.form.name': 'Fulde Navn',
    'contact.form.email': 'Email Adresse',
    'contact.form.subject': 'Emne',
    'contact.form.message': 'Besked',
    'contact.form.send': 'Send Besked',
    'contact.info': 'Kontakt Information',
    'contact.address': 'Adresse',
    'contact.phone': 'Telefon',
    'contact.email': 'Email',
    'contact.hours': 'Åbningstider',
    'footer.brand.desc': 'Håndlavede lædervarer med nordisk tradition og tidløs stil.',
    'footer.quicklinks': 'Hurtige Links',
    'footer.categories': 'Kategorier',
    'footer.contact': 'Kontakt',
    'footer.company': 'Nordic Leather Co.',
    'footer.location': 'Stockholm, Sverige',
    'footer.copyright': '© 2024 Nordic Leather. Alle rettigheder forbeholdt.',
    'footer.privacy': 'Privatlivspolitik',
    'footer.terms': 'Servicevilkår',
    'common.featured': 'Udvalgt Samling',
    'common.new': 'Ny',
    'common.viewDetails': 'Se Detaljer',
    'common.discover': 'Opdag vores samling af håndlavede lædervarer, hvert stykke fortæller sin egen historie om nordisk tradition.'
  },
  fi: {
    'nav.home': 'Koti',
    'nav.products': 'Tuotteet',
    'nav.about': 'Meistä',
    'nav.contact': 'Yhteystiedot',
    'nav.admin': 'Admin',
    'nav.cart': 'Ostoskori',
    'nav.categories': 'Kategoriat',
    'nav.settings': 'Asetukset',
    'nav.wishlist': 'Toivelista',
    'categories.bags': 'Laukut',
    'categories.wallets': 'Lompakot',
    'categories.belts': 'Vyöt',
    'categories.jackets': 'Takit',
    'categories.accessories': 'Lisävarusteet',
    'search.placeholder': 'Etsi tuotteita...',
    'search.title': 'Etsi Tuotteita',
    'promo.freeShipping': 'Ilmainen toimitus yli €100 tilauksille',
    'promo.support': '24/7 Asiakastuki',
    'theme.light': 'Vaalea tila',
    'theme.dark': 'Tumma tila',
    'hero.title': 'Premium Nahkatuotteet',
    'hero.subtitle': 'Käsintehty pohjoismaisen perinteen ja ajattoman tyylin mukaan',
    'hero.cta': 'Osta Kokoelma',
    'products.title': 'Kokoelmamme',
    'products.filter': 'Suodata Kategorian mukaan',
    'products.all': 'Kaikki Tuotteet',
    'products.bags': 'Laukut',
    'products.wallets': 'Lompakot',
    'products.belts': 'Vyöt',
    'products.jackets': 'Takit',
    'products.accessories': 'Lisävarusteet',
    'product.addToCart': 'Lisää Koriin',
    'product.price': 'Hinta',
    'product.size': 'Koko',
    'product.color': 'Väri',
    'admin.title': 'Admin Paneeli',
    'admin.products': 'Hallitse Tuotteita',
    'admin.orders': 'Tilaukset',
    'admin.customers': 'Asiakkaat',
    'cart.title': 'Ostoskori',
    'cart.empty': 'Ostoskorisi on tyhjä',
    'cart.total': 'Yhteensä',
    'cart.checkout': 'Kassalle',
    'about.title': 'Tietoa Nordic Leatherista',
    'about.subtitle': 'Luomme premium-nahkatuotteita pohjoismaisella perinteellä ja ajattomalla elegansilla vuodesta 1952.',
    'about.story': 'Tarinmme',
    'about.story.p1': 'Tukholman sydämessä perustettu Nordic Leather aloitti pienenä perhepajana, joka oli omistautunut säilyttämään vanhan nahkakäsityön taiteen. Perustajamme Erik Andersson uskoi, että todellinen laatu tulee kärsivällisyydestä, taidosta ja luonnonmateriaalien kunnioituksesta.',
    'about.story.p2': 'Nykyään jatkamme tätä perinnettä yhdistämällä ajan testaamia tekniikoita moderniin suunnitteluun luodaksemme nahkatuotteita, jotka kertovat tarinan pohjoismaisesta perinnöstä ja poikkeuksellisesta laadusta.',
    'about.values': 'Arvomme',
    'about.heritage': 'Pohjoismainen Perintö',
    'about.heritage.desc': 'Juurtunut skandinaaviseen perinteeseen ja käsityötaitoon',
    'about.sustainability': 'Kestävyys',
    'about.sustainability.desc': 'Eettinen hankinta ja ympäristötietoiset käytännöt',
    'about.quality': 'Laatu',
    'about.quality.desc': 'Huolellinen huomio yksityiskohtiin jokaisessa kappaleessa',
    'contact.title': 'Ota Yhteyttä',
    'contact.subtitle': 'Onko sinulla kysymys tai haluatko tietää lisää käsintehdyistä pohjoismaisista nahkatuotteistamme? Haluaisimme kuulla sinusta.',
    'contact.form.name': 'Koko Nimi',
    'contact.form.email': 'Sähköpostiosoite',
    'contact.form.subject': 'Aihe',
    'contact.form.message': 'Viesti',
    'contact.form.send': 'Lähetä Viesti',
    'contact.info': 'Yhteystiedot',
    'contact.address': 'Osoite',
    'contact.phone': 'Puhelin',
    'contact.email': 'Sähköposti',
    'contact.hours': 'Aukioloajat',
    'footer.brand.desc': 'Käsintehtyjä nahkatuotteita pohjoismaisella perinteellä ja ajattomalla tyylillä.',
    'footer.quicklinks': 'Pikalinkit',
    'footer.categories': 'Kategoriat',
    'footer.contact': 'Yhteystiedot',
    'footer.company': 'Nordic Leather Co.',
    'footer.location': 'Tukholma, Ruotsi',
    'footer.copyright': '© 2024 Nordic Leather. Kaikki oikeudet pidätetään.',
    'footer.privacy': 'Tietosuojakäytäntö',
    'footer.terms': 'Käyttöehdot',
    'common.featured': 'Esiteltyjä Kokoelma',
    'common.new': 'Uusi',
    'common.viewDetails': 'Katso Tiedot',
    'common.discover': 'Tutustu kokoelmaamme käsintehtyjä nahkatuotteita, joista jokainen kertoo oman tarinansa pohjoismaisesta perinteestä.'
  },
  is: {
    'nav.home': 'Heim',
    'nav.products': 'Vörur',
    'nav.about': 'Um okkur',
    'nav.contact': 'Samband',
    'nav.admin': 'Stjórnandi',
    'nav.cart': 'Karfa',
    'nav.categories': 'Flokkar',
    'nav.settings': 'Stillingar',
    'nav.wishlist': 'Óskalistí',
    'categories.bags': 'Töskur',
    'categories.wallets': 'Veski',
    'categories.belts': 'Belti',
    'categories.jackets': 'Jakkar',
    'categories.accessories': 'Fylgihlutir',
    'search.placeholder': 'Leita að vörum...',
    'search.title': 'Leita Vörur',
    'promo.freeShipping': 'Ókeypis sending á pantanir yfir €100',
    'promo.support': '24/7 Þjónustuver',
    'theme.light': 'Ljós ham',
    'theme.dark': 'Dökk ham',
    'hero.title': 'Úrvals Leðurvörur',
    'hero.subtitle': 'Handgerðar með norrænum hefðum og tímalausum stíl',
    'hero.cta': 'Kaupa Safn',
    'products.title': 'Safnið Okkar',
    'products.filter': 'Sía eftir Flokki',
    'products.all': 'Allar Vörur',
    'products.bags': 'Töskur',
    'products.wallets': 'Veski',
    'products.belts': 'Belti',
    'products.jackets': 'Jakkar',
    'products.accessories': 'Fylgihlutir',
    'product.addToCart': 'Bæta í Körfu',
    'product.price': 'Verð',
    'product.size': 'Stærð',
    'product.color': 'Litur',
    'admin.title': 'Stjórnborð',
    'admin.products': 'Stjórna Vörum',
    'admin.orders': 'Pantanir',
    'admin.customers': 'Viðskiptavinir',
    'cart.title': 'Innkaupakörfu',
    'cart.empty': 'Körfan þín er tóm',
    'cart.total': 'Samtals',
    'cart.checkout': 'Til greiðslu',
    'about.title': 'Um Nordic Leather',
    'about.subtitle': 'Búa til úrvals leðurvörur með norrænum hefðum og tímalausri glæsileika síðan 1952.',
    'about.story': 'Saga Okkar',
    'about.story.p1': 'Stofnað í hjarta Stokkhólms, Nordic Leather byrjaði sem lítil fjölskylduverkstæði tileinkuð því að varðveita fornleikinn á leðursmíði. Stofnandi okkar, Erik Andersson, trúði því að raunveruleg gæði komi frá þolinmæði, færni og virðingu fyrir náttúrulegum efnum.',
    'about.story.p2': 'Í dag höldum við þessari hefð áfram og sameinum gamalgrónar aðferðir við nútímalega hönnun til að búa til leðurvörur sem segja sögu af norrænum arfi og óvenjulegum gæðum.',
    'about.values': 'Gildi Okkar',
    'about.heritage': 'Norrænn Arfur',
    'about.heritage.desc': 'Rótgróið í skandinavískum hefðum og handverki',
    'about.sustainability': 'Sjálfbærni',
    'about.sustainability.desc': 'Siðferðileg innkaup og umhverfisvænar aðferðir',
    'about.quality': 'Gæði',
    'about.quality.desc': 'Vandlega athygli á smáatriðum í hverju stykki',
    'contact.title': 'Hafðu Samband',
    'contact.subtitle': 'Áttu spurningu eða vilt læra meira um handgerðar norrænar leðurvörur okkar? Við myndum elska að heyra frá þér.',
    'contact.form.name': 'Fullt Nafn',
    'contact.form.email': 'Netfang',
    'contact.form.subject': 'Efni',
    'contact.form.message': 'Skilaboð',
    'contact.form.send': 'Senda Skilaboð',
    'contact.info': 'Sambandsupplýsingar',
    'contact.address': 'Heimilisfang',
    'contact.phone': 'Sími',
    'contact.email': 'Netfang',
    'contact.hours': 'Opnunartímar',
    'footer.brand.desc': 'Handgerðar leðurvörur með norrænum hefðum og tímalausum stíl.',
    'footer.quicklinks': 'Flýtileiðir',
    'footer.categories': 'Flokkar',
    'footer.contact': 'Samband',
    'footer.company': 'Nordic Leather Co.',
    'footer.location': 'Stokkhólmur, Svíþjóð',
    'footer.copyright': '© 2024 Nordic Leather. Allur réttur áskilinn.',
    'footer.privacy': 'Persónuverndarstefna',
    'footer.terms': 'Þjónustuskilmálar',
    'common.featured': 'Úrvals Safn',
    'common.new': 'Nýtt',
    'common.viewDetails': 'Skoða Upplýsingar',
    'common.discover': 'Uppgötvaðu safn okkar af handgerðum leðurvörum, hvert stykki segir sína eigin sögu af norrænum hefðum.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const currentTranslations = translations[language];
    const fallbackTranslations = translations['en'];
    return currentTranslations[key as keyof typeof translations['en']] || 
           fallbackTranslations[key as keyof typeof translations['en']] || 
           key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};