export interface Country {
  code: string;
  name: string;
  phoneCode: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AD', name: 'Andorra', phoneCode: '+376', flag: '🇦🇩' },
  { code: 'AE', name: 'United Arab Emirates', phoneCode: '+971', flag: '🇦🇪' },
  { code: 'AF', name: 'Afghanistan', phoneCode: '+93', flag: '🇦🇫' },
  { code: 'AG', name: 'Antigua and Barbuda', phoneCode: '+1268', flag: '🇦🇬' },
  { code: 'AI', name: 'Anguilla', phoneCode: '+1264', flag: '🇦🇮' },
  { code: 'AL', name: 'Albania', phoneCode: '+355', flag: '🇦🇱' },
  { code: 'AM', name: 'Armenia', phoneCode: '+374', flag: '🇦🇲' },
  { code: 'AO', name: 'Angola', phoneCode: '+244', flag: '🇦🇴' },
  { code: 'AQ', name: 'Antarctica', phoneCode: '+672', flag: '🇦🇶' },
  { code: 'AR', name: 'Argentina', phoneCode: '+54', flag: '🇦🇷' },
  { code: 'AS', name: 'American Samoa', phoneCode: '+1684', flag: '🇦🇸' },
  { code: 'AT', name: 'Austria', phoneCode: '+43', flag: '🇦🇹' },
  { code: 'AU', name: 'Australia', phoneCode: '+61', flag: '🇦🇺' },
  { code: 'AW', name: 'Aruba', phoneCode: '+297', flag: '🇦🇼' },
  { code: 'AX', name: 'Åland Islands', phoneCode: '+358', flag: '🇦🇽' },
  { code: 'AZ', name: 'Azerbaijan', phoneCode: '+994', flag: '🇦🇿' },
  { code: 'BA', name: 'Bosnia and Herzegovina', phoneCode: '+387', flag: '🇧🇦' },
  { code: 'BB', name: 'Barbados', phoneCode: '+1246', flag: '🇧🇧' },
  { code: 'BD', name: 'Bangladesh', phoneCode: '+880', flag: '🇧🇩' },
  { code: 'BE', name: 'Belgium', phoneCode: '+32', flag: '🇧🇪' },
  { code: 'BF', name: 'Burkina Faso', phoneCode: '+226', flag: '🇧🇫' },
  { code: 'BG', name: 'Bulgaria', phoneCode: '+359', flag: '🇧🇬' },
  { code: 'BH', name: 'Bahrain', phoneCode: '+973', flag: '🇧🇭' },
  { code: 'BI', name: 'Burundi', phoneCode: '+257', flag: '🇧🇮' },
  { code: 'BJ', name: 'Benin', phoneCode: '+229', flag: '🇧🇯' },
  { code: 'BL', name: 'Saint Barthélemy', phoneCode: '+590', flag: '🇧🇱' },
  { code: 'BM', name: 'Bermuda', phoneCode: '+1441', flag: '🇧🇲' },
  { code: 'BN', name: 'Brunei', phoneCode: '+673', flag: '🇧🇳' },
  { code: 'BO', name: 'Bolivia', phoneCode: '+591', flag: '🇧🇴' },
  { code: 'BQ', name: 'Caribbean Netherlands', phoneCode: '+599', flag: '🇧🇶' },
  { code: 'BR', name: 'Brazil', phoneCode: '+55', flag: '🇧🇷' },
  { code: 'BS', name: 'Bahamas', phoneCode: '+1242', flag: '🇧🇸' },
  { code: 'BT', name: 'Bhutan', phoneCode: '+975', flag: '🇧🇹' },
  { code: 'BV', name: 'Bouvet Island', phoneCode: '+47', flag: '🇧🇻' },
  { code: 'BW', name: 'Botswana', phoneCode: '+267', flag: '🇧🇼' },
  { code: 'BY', name: 'Belarus', phoneCode: '+375', flag: '🇧🇾' },
  { code: 'BZ', name: 'Belize', phoneCode: '+501', flag: '🇧🇿' },
  { code: 'CA', name: 'Canada', phoneCode: '+1', flag: '🇨🇦' },
  { code: 'CC', name: 'Cocos Islands', phoneCode: '+61', flag: '🇨🇨' },
  { code: 'CD', name: 'Democratic Republic of the Congo', phoneCode: '+243', flag: '🇨🇩' },
  { code: 'CF', name: 'Central African Republic', phoneCode: '+236', flag: '🇨🇫' },
  { code: 'CG', name: 'Republic of the Congo', phoneCode: '+242', flag: '🇨🇬' },
  { code: 'CH', name: 'Switzerland', phoneCode: '+41', flag: '🇨🇭' },
  { code: 'CI', name: 'Côte d\'Ivoire', phoneCode: '+225', flag: '🇨🇮' },
  { code: 'CK', name: 'Cook Islands', phoneCode: '+682', flag: '🇨🇰' },
  { code: 'CL', name: 'Chile', phoneCode: '+56', flag: '🇨🇱' },
  { code: 'CM', name: 'Cameroon', phoneCode: '+237', flag: '🇨🇲' },
  { code: 'CN', name: 'China', phoneCode: '+86', flag: '🇨🇳' },
  { code: 'CO', name: 'Colombia', phoneCode: '+57', flag: '🇨🇴' },
  { code: 'CR', name: 'Costa Rica', phoneCode: '+506', flag: '🇨🇷' },
  { code: 'CU', name: 'Cuba', phoneCode: '+53', flag: '🇨🇺' },
  { code: 'CV', name: 'Cape Verde', phoneCode: '+238', flag: '🇨🇻' },
  { code: 'CW', name: 'Curaçao', phoneCode: '+599', flag: '🇨🇼' },
  { code: 'CX', name: 'Christmas Island', phoneCode: '+61', flag: '🇨🇽' },
  { code: 'CY', name: 'Cyprus', phoneCode: '+357', flag: '🇨🇾' },
  { code: 'CZ', name: 'Czech Republic', phoneCode: '+420', flag: '🇨🇿' },
  { code: 'DE', name: 'Germany', phoneCode: '+49', flag: '🇩🇪' },
  { code: 'DJ', name: 'Djibouti', phoneCode: '+253', flag: '🇩🇯' },
  { code: 'DK', name: 'Denmark', phoneCode: '+45', flag: '🇩🇰' },
  { code: 'DM', name: 'Dominica', phoneCode: '+1767', flag: '🇩🇲' },
  { code: 'DO', name: 'Dominican Republic', phoneCode: '+1809', flag: '🇩🇴' },
  { code: 'DZ', name: 'Algeria', phoneCode: '+213', flag: '🇩🇿' },
  { code: 'EC', name: 'Ecuador', phoneCode: '+593', flag: '🇪🇨' },
  { code: 'EE', name: 'Estonia', phoneCode: '+372', flag: '🇪🇪' },
  { code: 'EG', name: 'Egypt', phoneCode: '+20', flag: '🇪🇬' },
  { code: 'EH', name: 'Western Sahara', phoneCode: '+212', flag: '🇪🇭' },
  { code: 'ER', name: 'Eritrea', phoneCode: '+291', flag: '🇪🇷' },
  { code: 'ES', name: 'Spain', phoneCode: '+34', flag: '🇪🇸' },
  { code: 'ET', name: 'Ethiopia', phoneCode: '+251', flag: '🇪🇹' },
  { code: 'FI', name: 'Finland', phoneCode: '+358', flag: '🇫🇮' },
  { code: 'FJ', name: 'Fiji', phoneCode: '+679', flag: '🇫🇯' },
  { code: 'FK', name: 'Falkland Islands', phoneCode: '+500', flag: '🇫🇰' },
  { code: 'FM', name: 'Micronesia', phoneCode: '+691', flag: '🇫🇲' },
  { code: 'FO', name: 'Faroe Islands', phoneCode: '+298', flag: '🇫🇴' },
  { code: 'FR', name: 'France', phoneCode: '+33', flag: '🇫🇷' },
  { code: 'GA', name: 'Gabon', phoneCode: '+241', flag: '🇬🇦' },
  { code: 'GB', name: 'United Kingdom', phoneCode: '+44', flag: '🇬🇧' },
  { code: 'GD', name: 'Grenada', phoneCode: '+1473', flag: '🇬🇩' },
  { code: 'GE', name: 'Georgia', phoneCode: '+995', flag: '🇬🇪' },
  { code: 'GF', name: 'French Guiana', phoneCode: '+594', flag: '🇬🇫' },
  { code: 'GG', name: 'Guernsey', phoneCode: '+44', flag: '🇬🇬' },
  { code: 'GH', name: 'Ghana', phoneCode: '+233', flag: '🇬🇭' },
  { code: 'GI', name: 'Gibraltar', phoneCode: '+350', flag: '🇬🇮' },
  { code: 'GL', name: 'Greenland', phoneCode: '+299', flag: '🇬🇱' },
  { code: 'GM', name: 'Gambia', phoneCode: '+220', flag: '🇬🇲' },
  { code: 'GN', name: 'Guinea', phoneCode: '+224', flag: '🇬🇳' },
  { code: 'GP', name: 'Guadeloupe', phoneCode: '+590', flag: '🇬🇵' },
  { code: 'GQ', name: 'Equatorial Guinea', phoneCode: '+240', flag: '🇬🇶' },
  { code: 'GR', name: 'Greece', phoneCode: '+30', flag: '🇬🇷' },
  { code: 'GS', name: 'South Georgia', phoneCode: '+500', flag: '🇬🇸' },
  { code: 'GT', name: 'Guatemala', phoneCode: '+502', flag: '🇬🇹' },
  { code: 'GU', name: 'Guam', phoneCode: '+1671', flag: '🇬🇺' },
  { code: 'GW', name: 'Guinea-Bissau', phoneCode: '+245', flag: '🇬🇼' },
  { code: 'GY', name: 'Guyana', phoneCode: '+592', flag: '🇬🇾' },
  { code: 'HK', name: 'Hong Kong', phoneCode: '+852', flag: '🇭🇰' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', phoneCode: '+672', flag: '🇭🇲' },
  { code: 'HN', name: 'Honduras', phoneCode: '+504', flag: '🇭🇳' },
  { code: 'HR', name: 'Croatia', phoneCode: '+385', flag: '🇭🇷' },
  { code: 'HT', name: 'Haiti', phoneCode: '+509', flag: '🇭🇹' },
  { code: 'HU', name: 'Hungary', phoneCode: '+36', flag: '🇭🇺' },
  { code: 'ID', name: 'Indonesia', phoneCode: '+62', flag: '🇮🇩' },
  { code: 'IE', name: 'Ireland', phoneCode: '+353', flag: '🇮🇪' },
  { code: 'IL', name: 'Israel', phoneCode: '+972', flag: '🇮🇱' },
  { code: 'IM', name: 'Isle of Man', phoneCode: '+44', flag: '🇮🇲' },
  { code: 'IN', name: 'India', phoneCode: '+91', flag: '🇮🇳' },
  { code: 'IO', name: 'British Indian Ocean Territory', phoneCode: '+246', flag: '🇮🇴' },
  { code: 'IQ', name: 'Iraq', phoneCode: '+964', flag: '🇮🇶' },
  { code: 'IR', name: 'Iran', phoneCode: '+98', flag: '🇮🇷' },
  { code: 'IS', name: 'Iceland', phoneCode: '+354', flag: '🇮🇸' },
  { code: 'IT', name: 'Italy', phoneCode: '+39', flag: '🇮🇹' },
  { code: 'JE', name: 'Jersey', phoneCode: '+44', flag: '🇯🇪' },
  { code: 'JM', name: 'Jamaica', phoneCode: '+1876', flag: '🇯🇲' },
  { code: 'JO', name: 'Jordan', phoneCode: '+962', flag: '🇯🇴' },
  { code: 'JP', name: 'Japan', phoneCode: '+81', flag: '🇯🇵' },
  { code: 'KE', name: 'Kenya', phoneCode: '+254', flag: '🇰🇪' },
  { code: 'KG', name: 'Kyrgyzstan', phoneCode: '+996', flag: '🇰🇬' },
  { code: 'KH', name: 'Cambodia', phoneCode: '+855', flag: '🇰🇭' },
  { code: 'KI', name: 'Kiribati', phoneCode: '+686', flag: '🇰🇮' },
  { code: 'KM', name: 'Comoros', phoneCode: '+269', flag: '🇰🇲' },
  { code: 'KN', name: 'Saint Kitts and Nevis', phoneCode: '+1869', flag: '🇰🇳' },
  { code: 'KP', name: 'North Korea', phoneCode: '+850', flag: '🇰🇵' },
  { code: 'KR', name: 'South Korea', phoneCode: '+82', flag: '🇰🇷' },
  { code: 'KW', name: 'Kuwait', phoneCode: '+965', flag: '🇰🇼' },
  { code: 'KY', name: 'Cayman Islands', phoneCode: '+1345', flag: '🇰🇾' },
  { code: 'KZ', name: 'Kazakhstan', phoneCode: '+7', flag: '🇰🇿' },
  { code: 'LA', name: 'Laos', phoneCode: '+856', flag: '🇱🇦' },
  { code: 'LB', name: 'Lebanon', phoneCode: '+961', flag: '🇱🇧' },
  { code: 'LC', name: 'Saint Lucia', phoneCode: '+1758', flag: '🇱🇨' },
  { code: 'LI', name: 'Liechtenstein', phoneCode: '+423', flag: '🇱🇮' },
  { code: 'LK', name: 'Sri Lanka', phoneCode: '+94', flag: '🇱🇰' },
  { code: 'LR', name: 'Liberia', phoneCode: '+231', flag: '🇱🇷' },
  { code: 'LS', name: 'Lesotho', phoneCode: '+266', flag: '🇱🇸' },
  { code: 'LT', name: 'Lithuania', phoneCode: '+370', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', phoneCode: '+352', flag: '🇱🇺' },
  { code: 'LV', name: 'Latvia', phoneCode: '+371', flag: '🇱🇻' },
  { code: 'LY', name: 'Libya', phoneCode: '+218', flag: '🇱🇾' },
  { code: 'MA', name: 'Morocco', phoneCode: '+212', flag: '🇲🇦' },
  { code: 'MC', name: 'Monaco', phoneCode: '+377', flag: '🇲🇨' },
  { code: 'MD', name: 'Moldova', phoneCode: '+373', flag: '🇲🇩' },
  { code: 'ME', name: 'Montenegro', phoneCode: '+382', flag: '🇲🇪' },
  { code: 'MF', name: 'Saint Martin', phoneCode: '+590', flag: '🇲🇫' },
  { code: 'MG', name: 'Madagascar', phoneCode: '+261', flag: '🇲🇬' },
  { code: 'MH', name: 'Marshall Islands', phoneCode: '+692', flag: '🇲🇭' },
  { code: 'MK', name: 'North Macedonia', phoneCode: '+389', flag: '🇲🇰' },
  { code: 'ML', name: 'Mali', phoneCode: '+223', flag: '🇲🇱' },
  { code: 'MM', name: 'Myanmar', phoneCode: '+95', flag: '🇲🇲' },
  { code: 'MN', name: 'Mongolia', phoneCode: '+976', flag: '🇲🇳' },
  { code: 'MO', name: 'Macao', phoneCode: '+853', flag: '🇲🇴' },
  { code: 'MP', name: 'Northern Mariana Islands', phoneCode: '+1670', flag: '🇲🇵' },
  { code: 'MQ', name: 'Martinique', phoneCode: '+596', flag: '🇲🇶' },
  { code: 'MR', name: 'Mauritania', phoneCode: '+222', flag: '🇲🇷' },
  { code: 'MS', name: 'Montserrat', phoneCode: '+1664', flag: '🇲🇸' },
  { code: 'MT', name: 'Malta', phoneCode: '+356', flag: '🇲🇹' },
  { code: 'MU', name: 'Mauritius', phoneCode: '+230', flag: '🇲🇺' },
  { code: 'MV', name: 'Maldives', phoneCode: '+960', flag: '🇲🇻' },
  { code: 'MW', name: 'Malawi', phoneCode: '+265', flag: '🇲🇼' },
  { code: 'MX', name: 'Mexico', phoneCode: '+52', flag: '🇲🇽' },
  { code: 'MY', name: 'Malaysia', phoneCode: '+60', flag: '🇲🇾' },
  { code: 'MZ', name: 'Mozambique', phoneCode: '+258', flag: '🇲🇿' },
  { code: 'NA', name: 'Namibia', phoneCode: '+264', flag: '🇳🇦' },
  { code: 'NC', name: 'New Caledonia', phoneCode: '+687', flag: '🇳🇨' },
  { code: 'NE', name: 'Niger', phoneCode: '+227', flag: '🇳🇪' },
  { code: 'NF', name: 'Norfolk Island', phoneCode: '+672', flag: '🇳🇫' },
  { code: 'NG', name: 'Nigeria', phoneCode: '+234', flag: '🇳🇬' },
  { code: 'NI', name: 'Nicaragua', phoneCode: '+505', flag: '🇳🇮' },
  { code: 'NL', name: 'Netherlands', phoneCode: '+31', flag: '🇳🇱' },
  { code: 'NO', name: 'Norway', phoneCode: '+47', flag: '🇳🇴' },
  { code: 'NP', name: 'Nepal', phoneCode: '+977', flag: '🇳🇵' },
  { code: 'NR', name: 'Nauru', phoneCode: '+674', flag: '🇳🇷' },
  { code: 'NU', name: 'Niue', phoneCode: '+683', flag: '🇳🇺' },
  { code: 'NZ', name: 'New Zealand', phoneCode: '+64', flag: '🇳🇿' },
  { code: 'OM', name: 'Oman', phoneCode: '+968', flag: '🇴🇲' },
  { code: 'PA', name: 'Panama', phoneCode: '+507', flag: '🇵🇦' },
  { code: 'PE', name: 'Peru', phoneCode: '+51', flag: '🇵🇪' },
  { code: 'PF', name: 'French Polynesia', phoneCode: '+689', flag: '🇵🇫' },
  { code: 'PG', name: 'Papua New Guinea', phoneCode: '+675', flag: '🇵🇬' },
  { code: 'PH', name: 'Philippines', phoneCode: '+63', flag: '🇵🇭' },
  { code: 'PK', name: 'Pakistan', phoneCode: '+92', flag: '🇵🇰' },
  { code: 'PL', name: 'Poland', phoneCode: '+48', flag: '🇵🇱' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', phoneCode: '+508', flag: '🇵🇲' },
  { code: 'PN', name: 'Pitcairn', phoneCode: '+64', flag: '🇵🇳' },
  { code: 'PR', name: 'Puerto Rico', phoneCode: '+1787', flag: '🇵🇷' },
  { code: 'PS', name: 'Palestine', phoneCode: '+970', flag: '🇵🇸' },
  { code: 'PT', name: 'Portugal', phoneCode: '+351', flag: '🇵🇹' },
  { code: 'PW', name: 'Palau', phoneCode: '+680', flag: '🇵🇼' },
  { code: 'PY', name: 'Paraguay', phoneCode: '+595', flag: '🇵🇾' },
  { code: 'QA', name: 'Qatar', phoneCode: '+974', flag: '🇶🇦' },
  { code: 'RE', name: 'Réunion', phoneCode: '+262', flag: '🇷🇪' },
  { code: 'RO', name: 'Romania', phoneCode: '+40', flag: '🇷🇴' },
  { code: 'RS', name: 'Serbia', phoneCode: '+381', flag: '🇷🇸' },
  { code: 'RU', name: 'Russia', phoneCode: '+7', flag: '🇷🇺' },
  { code: 'RW', name: 'Rwanda', phoneCode: '+250', flag: '🇷🇼' },
  { code: 'SA', name: 'Saudi Arabia', phoneCode: '+966', flag: '🇸🇦' },
  { code: 'SB', name: 'Solomon Islands', phoneCode: '+677', flag: '🇸🇧' },
  { code: 'SC', name: 'Seychelles', phoneCode: '+248', flag: '🇸🇨' },
  { code: 'SD', name: 'Sudan', phoneCode: '+249', flag: '🇸🇩' },
  { code: 'SE', name: 'Sweden', phoneCode: '+46', flag: '🇸🇪' },
  { code: 'SG', name: 'Singapore', phoneCode: '+65', flag: '🇸🇬' },
  { code: 'SH', name: 'Saint Helena', phoneCode: '+290', flag: '🇸🇭' },
  { code: 'SI', name: 'Slovenia', phoneCode: '+386', flag: '🇸🇮' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', phoneCode: '+47', flag: '🇸🇯' },
  { code: 'SK', name: 'Slovakia', phoneCode: '+421', flag: '🇸🇰' },
  { code: 'SL', name: 'Sierra Leone', phoneCode: '+232', flag: '🇸🇱' },
  { code: 'SM', name: 'San Marino', phoneCode: '+378', flag: '🇸🇲' },
  { code: 'SN', name: 'Senegal', phoneCode: '+221', flag: '🇸🇳' },
  { code: 'SO', name: 'Somalia', phoneCode: '+252', flag: '🇸🇴' },
  { code: 'SR', name: 'Suriname', phoneCode: '+597', flag: '🇸🇷' },
  { code: 'SS', name: 'South Sudan', phoneCode: '+211', flag: '🇸🇸' },
  { code: 'ST', name: 'São Tomé and Príncipe', phoneCode: '+239', flag: '🇸🇹' },
  { code: 'SV', name: 'El Salvador', phoneCode: '+503', flag: '🇸🇻' },
  { code: 'SX', name: 'Sint Maarten', phoneCode: '+1721', flag: '🇸🇽' },
  { code: 'SY', name: 'Syria', phoneCode: '+963', flag: '🇸🇾' },
  { code: 'SZ', name: 'Eswatini', phoneCode: '+268', flag: '🇸🇿' },
  { code: 'TC', name: 'Turks and Caicos Islands', phoneCode: '+1649', flag: '🇹🇨' },
  { code: 'TD', name: 'Chad', phoneCode: '+235', flag: '🇹🇩' },
  { code: 'TF', name: 'French Southern Territories', phoneCode: '+262', flag: '🇹🇫' },
  { code: 'TG', name: 'Togo', phoneCode: '+228', flag: '🇹🇬' },
  { code: 'TH', name: 'Thailand', phoneCode: '+66', flag: '🇹🇭' },
  { code: 'TJ', name: 'Tajikistan', phoneCode: '+992', flag: '🇹🇯' },
  { code: 'TK', name: 'Tokelau', phoneCode: '+690', flag: '🇹🇰' },
  { code: 'TL', name: 'Timor-Leste', phoneCode: '+670', flag: '🇹🇱' },
  { code: 'TM', name: 'Turkmenistan', phoneCode: '+993', flag: '🇹🇲' },
  { code: 'TN', name: 'Tunisia', phoneCode: '+216', flag: '🇹🇳' },
  { code: 'TO', name: 'Tonga', phoneCode: '+676', flag: '🇹🇴' },
  { code: 'TR', name: 'Turkey', phoneCode: '+90', flag: '🇹🇷' },
  { code: 'TT', name: 'Trinidad and Tobago', phoneCode: '+1868', flag: '🇹🇹' },
  { code: 'TV', name: 'Tuvalu', phoneCode: '+688', flag: '🇹🇻' },
  { code: 'TW', name: 'Taiwan', phoneCode: '+886', flag: '🇹🇼' },
  { code: 'TZ', name: 'Tanzania', phoneCode: '+255', flag: '🇹🇿' },
  { code: 'UA', name: 'Ukraine', phoneCode: '+380', flag: '🇺🇦' },
  { code: 'UG', name: 'Uganda', phoneCode: '+256', flag: '🇺🇬' },
  { code: 'UM', name: 'United States Minor Outlying Islands', phoneCode: '+1', flag: '🇺🇲' },
  { code: 'US', name: 'United States', phoneCode: '+1', flag: '🇺🇸' },
  { code: 'UY', name: 'Uruguay', phoneCode: '+598', flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistan', phoneCode: '+998', flag: '🇺🇿' },
  { code: 'VA', name: 'Vatican City', phoneCode: '+39', flag: '🇻🇦' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', phoneCode: '+1784', flag: '🇻🇨' },
  { code: 'VE', name: 'Venezuela', phoneCode: '+58', flag: '🇻🇪' },
  { code: 'VG', name: 'British Virgin Islands', phoneCode: '+1284', flag: '🇻🇬' },
  { code: 'VI', name: 'U.S. Virgin Islands', phoneCode: '+1340', flag: '🇻🇮' },
  { code: 'VN', name: 'Vietnam', phoneCode: '+84', flag: '🇻🇳' },
  { code: 'VU', name: 'Vanuatu', phoneCode: '+678', flag: '🇻🇺' },
  { code: 'WF', name: 'Wallis and Futuna', phoneCode: '+681', flag: '🇼🇫' },
  { code: 'WS', name: 'Samoa', phoneCode: '+685', flag: '🇼🇸' },
  { code: 'YE', name: 'Yemen', phoneCode: '+967', flag: '🇾🇪' },
  { code: 'YT', name: 'Mayotte', phoneCode: '+262', flag: '🇾🇹' },
  { code: 'ZA', name: 'South Africa', phoneCode: '+27', flag: '🇿🇦' },
  { code: 'ZM', name: 'Zambia', phoneCode: '+260', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', phoneCode: '+263', flag: '🇿🇼' }
];

// Nordic countries for priority display
export const NORDIC_COUNTRIES = ['FI', 'NO', 'SE', 'DK', 'IS'];

export const getCountryByCode = (code: string): Country | undefined => {
  return COUNTRIES.find(country => country.code === code);
};

export const getCountryByName = (name: string): Country | undefined => {
  return COUNTRIES.find(country => country.name.toLowerCase() === name.toLowerCase());
};

export const getPhoneCodeByCountry = (countryName: string): string => {
  const country = getCountryByName(countryName);
  return country?.phoneCode || '+1';
};

export const getPhoneCodeByCountryCode = (countryCode: string): string => {
  const country = getCountryByCode(countryCode);
  return country?.phoneCode || '+358'; // Default to Finland's phone code
};

// Map currencies to their primary country codes
export const getCurrencyPrimaryCountry = (currency: string): string => {
  const currencyToCountryMap: Record<string, string> = {
    // Major Currencies
    'EUR': 'DE', // Germany (largest EU economy)
    'USD': 'US',
    'GBP': 'GB',
    'JPY': 'JP',
    'CNY': 'CN',
    'AUD': 'AU',
    'CAD': 'CA',
    'CHF': 'CH',
    
    // European
    'SEK': 'SE',
    'NOK': 'NO',
    'DKK': 'DK',
    'PLN': 'PL',
    'CZK': 'CZ',
    'HUF': 'HU',
    'RON': 'RO',
    'BGN': 'BG',
    'HRK': 'HR',
    'ISK': 'IS',
    
    // Asia Pacific
    'HKD': 'HK',
    'SGD': 'SG',
    'NZD': 'NZ',
    'KRW': 'KR',
    'TWD': 'TW',
    'THB': 'TH',
    'MYR': 'MY',
    'PHP': 'PH',
    'IDR': 'ID',
    'VND': 'VN',
    'INR': 'IN',
    'PKR': 'PK',
    'BDT': 'BD',
    'LKR': 'LK',
    
    // Americas
    'MXN': 'MX',
    'BRL': 'BR',
    'ARS': 'AR',
    'CLP': 'CL',
    'COP': 'CO',
    'PEN': 'PE',
    'UYU': 'UY',
    
    // Middle East & Africa
    'AED': 'AE',
    'SAR': 'SA',
    'QAR': 'QA',
    'KWD': 'KW',
    'BHD': 'BH',
    'OMR': 'OM',
    'JOD': 'JO',
    'ILS': 'IL',
    'EGP': 'EG',
    'ZAR': 'ZA',
    'NGN': 'NG',
    'KES': 'KE',
    'GHS': 'GH',
    'MAD': 'MA',
    'TND': 'TN',
    
    // Other Currencies
    'TRY': 'TR',
    'RUB': 'RU',
    'UAH': 'UA',
    'GEL': 'GE',
    'AMD': 'AM',
    'AZN': 'AZ',
    'KZT': 'KZ',
    'UZS': 'UZ',
    'MNT': 'MN',
    'NPR': 'NP',
    'MMK': 'MM',
    'KHR': 'KH',
    'LAK': 'LA',
    'BWP': 'BW',
    'MUR': 'MU',
    'SCR': 'SC',
  };
  
  return currencyToCountryMap[currency] || 'FI'; // Default to Finland
};